'use client';
import {useEffect,useState} from 'react';
import {newEdition} from '../../lib/schema';
import EditionView from '../components/EditionView';

async function api(data,id){
 const response=await fetch('/api/editor'+(id?'?id='+encodeURIComponent(id):''),data?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}:{cache:'no-store'});
 const result=await response.json();if(!response.ok)throw Object.assign(new Error(result.error||'Operazione non riuscita'),{status:response.status});return result;
}
export default function EditorApp({ready}){
 const [user,setUser]=useState(false),[role,setRole]=useState(''),[drafts,setDrafts]=useState([]),[current,setCurrent]=useState(null);
 const [dirty,setDirty]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(ready);
 const [preview,setPreview]=useState(false);
 async function refreshList(){const data=await api();setDrafts(data.drafts);setRole(data.role);setUser(true);}
 useEffect(()=>{if(!ready)return;refreshList().catch(e=>{if(e.status!==401)setError(e.message);}).finally(()=>setLoading(false));},[ready]);
 useEffect(()=>{const prevent=e=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',prevent);return()=>window.removeEventListener('beforeunload',prevent);},[dirty]);
 async function run(fn){setError('');setNotice('');setBusy(true);try{await fn();}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function login(e){e.preventDefault();const fields=new FormData(e.currentTarget);await run(async()=>{const r=await fetch('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:fields.get('username'),password:fields.get('password'),returnTo:new URLSearchParams(location.search).get('returnTo')})});const data=await r.json();if(!r.ok)throw new Error(data.error||'Accesso non riuscito.');location.assign(data.returnTo);});}
 const edit=(key,value)=>{setCurrent(c=>({...c,body:{...c.body,[key]:value}}));setDirty(true);};
 const editArticle=(id,patch)=>edit('articles',current.body.articles.map(a=>a.id===id?{...a,...patch}:a));
 async function open(id){if(dirty&&!confirm('Ci sono modifiche non salvate. Vuoi abbandonarle?'))return;await run(async()=>{setCurrent(await api(null,id));setDirty(false);setPreview(false);});}
 async function save(){await run(async()=>{const body={...current.body,keyPoints:current.body.keyPoints.map(s=>s.trim()).filter(Boolean),tones:current.body.tones.map(s=>s.trim()).filter(Boolean)};const result=await api({action:'save',id:current.id,version:current.version,body});setCurrent({...current,...result,revisions:[{version:result.version,created_at:result.updated_at},...current.revisions.filter(r=>r.version!==result.version)]});setDirty(false);setNotice('Bozza salvata online.');await refreshList();});}
 async function create(){if(dirty&&!confirm('Abbandonare le modifiche non salvate?'))return;await run(async()=>{const result=await api({action:'save',id:crypto.randomUUID(),version:0,body:newEdition()});setCurrent({...result,assets:[],revisions:[]});setDirty(false);setPreview(false);await refreshList();});}
 async function upload(file){if(!file)return;await run(async()=>{
  if(file.size>52428800||!file.name.toLowerCase().endsWith('.pdf'))throw new Error('Scegli un PDF fino a 50 MB.');
  const bytes=new Uint8Array(await file.slice(0,5).arrayBuffer());if(new TextDecoder().decode(bytes)!=='%PDF-')throw new Error('Il file non è un PDF valido.');
  const prepared=await api({action:'upload',id:current.id,name:file.name});
  const response=await fetch(prepared.uploadUrl,{method:'PUT',headers:{'Content-Type':'application/pdf'},body:file});if(!response.ok)throw new Error('Caricamento PDF non riuscito. Riprova con un nuovo caricamento.');
  setCurrent(c=>({...c,assets:[...c.assets,prepared.asset]}));setNotice('PDF originale salvato nell’archivio privato.');
 });}
 async function showAsset(assetId){await run(async()=>{const result=await api({action:'asset',assetId});window.open(result.url,'_blank','noopener,noreferrer');});}
 async function clip(article){await run(async()=>{if(!article.sourceId||!article.pages.length)throw new Error('Seleziona il PDF e indica le pagine.');const asset=await api({action:'clip',sourceId:article.sourceId,pages:article.pages});setCurrent(c=>({...c,assets:[...c.assets,asset],body:{...c.body,articles:c.body.articles.map(a=>a.id===article.id?{...a,clipId:asset.id}:a)}}));setDirty(true);setNotice('Ritaglio creato. Salva la bozza per confermare l’associazione.');});}
 if(!user)return <main className="editor-main narrow"><a className="editor-brand" href="/">JUMP <b>PRESS</b></a><p className="eyebrow">AREA RISERVATA</p><h1>La redazione,<br/>in un unico posto.</h1><p className="editor-intro">Rivedi le bozze, controlla i ritagli e pubblica la rassegna quando è pronta.</p>
 <form className="editor-card" onSubmit={login}><h2>Accedi alla redazione</h2>{!ready&&<p className="editor-notice" role="status">Area editor in preparazione. Gli accessi devono essere configurati.</p>}
 <label>Nome utente<input name="username" autoComplete="username" autoCapitalize="none" spellCheck={false} required maxLength={80} disabled={busy}/></label><label>Password<input name="password" type="password" autoComplete="current-password" required maxLength={256} disabled={busy}/></label>
 {error&&<p className="editor-error" role="alert">{error}</p>}<button disabled={!ready||busy||loading}>{loading?'Verifica accesso…':busy?'Accesso…':'Accedi'}</button><p className="editor-hint">Solo gli account autorizzati possono entrare.</p></form><a className="editor-return" href="/">← Torna alla rassegna pubblica</a></main>;
 return <main className="editor-main"><header className="editor-header"><div><a className="editor-brand" href="/">JUMP <b>PRESS</b></a><p className="eyebrow">REDAZIONE · {role==='publisher'?'EDITOR CON PUBBLICAZIONE':'EDITOR'}</p><h1>Le tue rassegne</h1></div><div className="editor-actions"><button disabled={busy} onClick={create}>Nuova bozza</button><button className="secondary" disabled={busy} onClick={()=>run(refreshList)}>Aggiorna elenco</button><button className="secondary" onClick={()=>run(async()=>{if(dirty&&!confirm('Uscire senza salvare?'))return;const response=await fetch('/api/auth/logout',{method:'POST'});if(!response.ok)throw new Error('Uscita non riuscita. Riprova.');setUser(false);setCurrent(null);setDrafts([]);setDirty(false);})}>Esci</button></div></header>
 {error&&<p className="editor-error" role="alert">{error} Le modifiche presenti nel modulo non sono state cancellate.</p>}{notice&&<p className="editor-notice" role="status">{notice}</p>}
 <div className="editor-workspace"><aside className="draft-list"><h2>Bozze online</h2>{!drafts.length&&<p>Non ci sono ancora bozze.</p>}{drafts.map(d=><button className={d.id===current?.id?'selected':''} key={d.id} onClick={()=>open(d.id)} disabled={busy}><b>{d.body.date}</b><span>{d.body.title}</span><small>Versione {d.version}</small></button>)}</aside>
 {!current?<section className="editor-card"><h2>Seleziona una bozza</h2><p>Puoi modificarla qui o dal tuo ChatGPT collegato a Jump Press.</p></section>:<fieldset disabled={busy} style={{border:0,padding:0,margin:0,minWidth:0}}>
 <div className="editor-toolbar"><span className="draft-badge">BOZZA · V{current.version}{dirty?' · NON SALVATA':''}</span><div className="editor-actions"><button disabled={busy||!dirty} onClick={save}>Salva bozza</button><button className="secondary" onClick={()=>setPreview(!preview)}>{preview?'Torna alla modifica':'Anteprima'}</button><button className="secondary" disabled={busy} onClick={()=>open(current.id)}>Ricarica</button></div></div>
 {preview?<EditionView body={current.body} preview onClip={showAsset}/>:<>
 <section className="editor-card"><h2>Edizione del giorno</h2><label>Data<input type="date" value={current.body.date} onChange={e=>edit('date',e.target.value)}/></label><label>Titolo<input value={current.body.title} onChange={e=>edit('title',e.target.value)}/></label><label>Sintesi della giornata<textarea rows={5} value={current.body.intro} onChange={e=>edit('intro',e.target.value)}/></label><label>Punti chiave · uno per riga<textarea value={current.body.keyPoints.join('\n')} onChange={e=>edit('keyPoints',e.target.value.split('\n'))}/></label><label>Toni prevalenti · uno per riga<textarea value={current.body.tones.join('\n')} onChange={e=>edit('tones',e.target.value.split('\n'))}/></label>
 <h3>Statistiche verificate</h3>{current.body.metrics.map((m,i)=><div className="metric-edit" key={i}><label>Dato<input value={m.label} onChange={e=>edit('metrics',current.body.metrics.map((x,j)=>j===i?{...x,label:e.target.value}:x))}/></label><label>Valore<input type="number" min="0" value={m.value} onChange={e=>edit('metrics',current.body.metrics.map((x,j)=>j===i?{...x,value:Number(e.target.value)}:x))}/></label><label>Riscontro nella fonte<input value={m.sourceNote} onChange={e=>edit('metrics',current.body.metrics.map((x,j)=>j===i?{...x,sourceNote:e.target.value}:x))}/></label><button className="secondary" onClick={()=>edit('metrics',current.body.metrics.filter((_,j)=>j!==i))}>Rimuovi dato</button></div>)}<button className="secondary" onClick={()=>edit('metrics',[...current.body.metrics,{label:'',value:0,sourceNote:''}])}>Aggiungi statistica</button></section>
 <section className="editor-card"><h2>PDF originali</h2><p>I documenti completi restano privati. Vengono pubblicati soltanto i ritagli associati agli articoli.</p><label>Carica PDF<input type="file" accept="application/pdf" disabled={busy} onChange={e=>{upload(e.target.files?.[0]);e.target.value='';}}/></label>{current.assets.filter(a=>a.kind==='source').map(a=><button className="file-link secondary" key={a.id} onClick={()=>showAsset(a.id)}>{a.name} ↗</button>)}</section>
 <div className="editor-section-heading"><h2>Articoli · {current.body.articles.length}</h2><button className="secondary" onClick={()=>edit('articles',[...current.body.articles,{id:crypto.randomUUID(),category:'Juventus',title:'',outlet:'',author:'',summary:'',rating:3,sourceId:null,clipId:null,pages:[]}])}>Aggiungi articolo</button></div>
 {current.body.articles.map((a,index)=><section className="editor-card" key={a.id}><div className="editor-section-heading"><h3>Articolo {index+1}</h3><div className="editor-actions"><button className="secondary" disabled={index===0} onClick={()=>{const list=[...current.body.articles];[list[index-1],list[index]]=[list[index],list[index-1]];edit('articles',list);}}>Sposta su</button><button className="secondary" onClick={()=>edit('articles',current.body.articles.filter(x=>x.id!==a.id))}>Rimuovi articolo</button></div></div>
 <div className="editor-grid"><label>Sezione<input value={a.category} onChange={e=>editArticle(a.id,{category:e.target.value})}/></label><label>Testata<input value={a.outlet} onChange={e=>editArticle(a.id,{outlet:e.target.value})}/></label></div><label>Titolo originale<input value={a.title} onChange={e=>editArticle(a.id,{title:e.target.value})}/></label><label>Autore · solo editoriali e analisi<input value={a.author} onChange={e=>editArticle(a.id,{author:e.target.value})}/></label><label>Riassunto<textarea rows={5} value={a.summary} onChange={e=>editArticle(a.id,{summary:e.target.value})}/></label><div className="editor-grid"><label>Peso editoriale<select value={a.rating} onChange={e=>editArticle(a.id,{rating:Number(e.target.value)})}>{[1,2,3,4,5].map(n=><option key={n} value={n}>{n} / 5</option>)}</select></label><label>PDF originale<select value={a.sourceId||''} onChange={e=>editArticle(a.id,{sourceId:e.target.value||null,clipId:null})}><option value="">Seleziona un PDF</option>{current.assets.filter(f=>f.kind==='source').map(f=><option value={f.id} key={f.id}>{f.name}</option>)}</select></label></div><label>Pagine · numeri separati da virgola, es. 12, 13<PagesInput value={a.pages} onChange={pages=>editArticle(a.id,{pages,clipId:null})}/></label><div className="editor-actions"><button className="secondary" disabled={busy} onClick={()=>clip(a)}>Crea ritaglio</button>{a.clipId&&<button className="secondary" disabled={busy} onClick={()=>showAsset(a.clipId)}>Apri ritaglio ↗</button>}</div></section>)}
 </>}
 <section className="editor-card"><h2>Pubblicazione</h2><p>Pubblica la versione salvata {current.version}. Le modifiche successive resteranno in bozza.</p><button disabled={busy||dirty||role!=='publisher'||!current.body.articles.length} onClick={()=>run(async()=>{const result=await api({action:'publish',id:current.id,version:current.version,confirmation:'PUBBLICA'});setNotice(result.alreadyPublished?'Questa versione era già stata pubblicata.':'Rassegna pubblicata.');})}>Pubblica versione {current.version}</button>{dirty&&<p>Salva le modifiche prima di pubblicare.</p>}{role!=='publisher'&&<p>Il tuo account può preparare bozze; la pubblicazione richiede un editor abilitato.</p>}</section>
 <section className="editor-card"><h2>Versioni precedenti</h2><p>Il ripristino crea una nuova bozza e non cambia il sito pubblico.</p><select aria-label="Versione da ripristinare" defaultValue="" disabled={busy||dirty} onChange={e=>{const revision=Number(e.target.value);e.target.value='';if(revision)run(async()=>{const row=await api({action:'restore',id:current.id,version:current.version,revision});setCurrent({...current,...row,revisions:[{version:row.version,created_at:row.updated_at},...current.revisions.filter(r=>r.version!==row.version)]});setDirty(false);setNotice('Revisione ripristinata come nuova bozza.');await refreshList();});}}><option value="">Scegli una versione…</option>{current.revisions.filter(r=>r.version!==current.version).map(r=><option key={r.version} value={r.version}>Versione {r.version} · {new Date(r.created_at).toLocaleString('it-IT')}</option>)}</select></section>
 </fieldset>}</div></main>;
}
function PagesInput({value,onChange}){const serialized=value.join(', ');const [text,setText]=useState(serialized);useEffect(()=>setText(serialized),[serialized]);return <input value={text} onChange={e=>setText(e.target.value)} onBlur={()=>{if(text!==serialized)onChange(text.trim()?text.split(',').map(x=>Number(x.trim())):[]);}} inputMode="numeric"/>;}
