'use client';
import {useEffect,useState} from 'react';
import EditionView from '../components/EditionView';
import AppControls from '../components/AppControls';
async function read(id){const r=await fetch('/api/editor'+(id?'?id='+encodeURIComponent(id):''),{cache:'no-store'});const data=await r.json();if(!r.ok)throw Object.assign(new Error(data.error||'Lettura non riuscita'),{status:r.status});return data;}
export default function EditorApp({ready}){
 const [role,setRole]=useState(''),[notice,setNotice]=useState('');
 const [user,setUser]=useState(false),[current,setCurrent]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(ready);
 useEffect(()=>{let active=true;if(!ready)return;async function load(){try{const list=await read();if(!active)return;setUser(true);setRole(list.role);const id=new URLSearchParams(location.search).get('draft')||list.drafts[0]?.id;if(id){const row=await read(id);if(active)setCurrent(row);}}catch(e){if(active&&e.status!==401)setError(e.message);}finally{if(active)setLoading(false);}}load();return()=>{active=false;};},[ready]);
 async function login(e){e.preventDefault();setBusy(true);setError('');const fields=new FormData(e.currentTarget);try{const query=new URLSearchParams(location.search);const r=await fetch('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:fields.get('username'),password:fields.get('password'),returnTo:query.get('returnTo')||location.pathname+location.search})});const data=await r.json();if(!r.ok)throw Error(data.error||'Accesso non riuscito');location.assign(data.returnTo);}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function showAsset(assetId){setError('');try{const r=await fetch('/api/editor',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'asset',assetId})});const data=await r.json();if(!r.ok)throw Error(data.error||'Ritaglio non disponibile');window.dispatchEvent(new CustomEvent('jump-open-clip',{detail:{url:data.url}}));}catch(e){setError(e.message);}}
 async function confirmDraft(){
  if(!current||busy||role!=='publisher')return;
  setBusy(true);setError('');setNotice('');
  try{const r=await fetch('/api/editor',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'publish',id:current.id,version:current.version,confirmation:'PUBBLICA'})});const result=await r.json();if(!r.ok)throw Error(result.error||'Pubblicazione non riuscita.');setCurrent(c=>({...c,publishedVersions:[...new Set([...(c.publishedVersions||[]),c.version])]}));setNotice('Rassegna pubblicata.');return true;}catch(e){setError(e.message);return false;}finally{setBusy(false);}
 }
 if(loading)return <main><p style={{color:'white'}} role="status">Caricamento rassegna…</p></main>;
 if(!user)return <div className="editor-shell"><main className="editor-main narrow"><a className="editor-brand" href="/">JUMP <b>PRESS</b></a><p className="eyebrow">AREA RISERVATA</p><h1>La redazione,<br/>in un unico posto.</h1><p className="editor-intro">Rivedi le bozze, controlla i ritagli e pubblica la rassegna quando è pronta.</p>
 <form className="editor-card" onSubmit={login}><h2>Accedi alla redazione</h2>{!ready&&<p className="editor-notice" role="status">Area editor in preparazione. Gli accessi devono essere configurati.</p>}
 <label>Nome utente<input name="username" autoComplete="username" autoCapitalize="none" spellCheck={false} required maxLength={80} disabled={busy}/></label><label>Password<input name="password" type="password" autoComplete="current-password" required maxLength={256} disabled={busy}/></label>
 {error&&<p className="editor-error" role="alert">{error}</p>}<button disabled={!ready||busy||loading}>{loading?'Verifica accesso…':busy?'Accesso…':'Accedi'}</button><p className="editor-hint">Solo gli account autorizzati possono entrare.</p></form><a className="editor-return" href="/">← Torna alla rassegna pubblica</a></main></div>;
 return <><AppControls onConfirm={current&&role==='publisher'&&!current.publishedVersions?.includes(current.version)?confirmDraft:undefined} confirmBusy={busy} confirmDate={current?.body.date} confirmVersion={current?.version}/><main>{notice&&<p role="status" className="editor-notice">{notice}</p>}{error&&<p className="editor-error" role="alert">{error}</p>}{current?<EditionView body={current.body} preview={!current.publishedVersions?.includes(current.version)} onClip={showAsset} privateClips/>:<section className="ranking"><h1 style={{fontSize:32,color:'#111'}}>Nessuna bozza disponibile</h1><p>La rassegna preparata tramite GPT apparirà qui.</p></section>}</main></>;
}
