'use client';
import {useRef,useState} from 'react';
export default function EditorActions({onDelete,onTrash,onRecover,onLogout,demo=false,date}){
 const menu=useRef(null),dialog=useRef(null),locked=useRef(false);
 const [mode,setMode]=useState('delete'),[rows,setRows]=useState([]),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function open(kind){menu.current.open=false;setMode(kind);setError('');dialog.current.showModal();if(kind==='trash'){setBusy(true);try{setRows(await onTrash());}catch(e){setError(e.message);}finally{setBusy(false);}}}
 async function act(fn){if(locked.current)return;locked.current=true;setBusy(true);setError('');try{await fn();dialog.current.close();}catch(e){setError(e.message);}finally{locked.current=false;setBusy(false);}}
 return <><details className="editor-more" ref={menu} onKeyDown={e=>{if(e.key==='Escape')menu.current.open=false;}} onBlur={e=>{if(!e.currentTarget.contains(e.relatedTarget))menu.current.open=false;}}><summary aria-label="Altre azioni editor">⋯</summary><div className="editor-menu"><a href={demo?'#istruzioni':'/editor/istruzioni'} onClick={demo?e=>{e.preventDefault();open('instructions');}:undefined}>Istruzioni</a><button onClick={()=>open('trash')}>Cestino</button>{onDelete&&<button className="danger-item" onClick={()=>open('delete')}>Elimina bozza</button>}<button onClick={()=>open('logout')}>Esci</button></div></details>
 <dialog className="publish-dialog" ref={dialog} aria-labelledby="editor-action-title" onCancel={e=>{if(busy)e.preventDefault();}}><div className="publish-dialog-brand"><span>JUMP</span> PRESS</div><p className="publish-dialog-label">{demo?'ANTEPRIMA LOCALE · NESSUN DATO ONLINE MODIFICATO':'REDAZIONE'}</p><h2 id="editor-action-title">{mode==='delete'?'Eliminare la bozza?':mode==='trash'?'Cestino':mode==='logout'?'Uscire dall’editor?':'Istruzioni'}</h2>
 {mode==='delete'&&<p>La bozza{date?' del '+new Intl.DateTimeFormat('it-IT',{dateStyle:'long',timeZone:'UTC'}).format(new Date(date+'T12:00:00Z')):''} verrà spostata nel cestino. Potrai recuperarla. Se GPT sta ancora lavorando su questa bozza, attendi che abbia finito.</p>}
 {mode==='instructions'&&<p>Nel sito questo collegamento apre le istruzioni di consegna. Questa anteprima resta separata dal lavoro online.</p>}
 {mode==='logout'&&<p>Potrai continuare a leggere la rassegna pubblica.</p>}
 {mode==='trash'&&(busy?<p role="status">Caricamento…</p>:rows.length?<ul className="trash-list">{rows.map(row=><li key={row.id}><div><b>{row.body.title}</b><small>{row.body.date}</small></div><button disabled={busy} onClick={()=>act(()=>onRecover(row))}>Ripristina</button></li>)}</ul>:!error&&<p>Il cestino è vuoto.</p>)}
 {error&&<p role="alert" className="publish-dialog-error">{error}</p>}<div className="publish-dialog-actions"><button className="publish-cancel" disabled={busy} onClick={()=>dialog.current.close()}>{mode==='trash'||mode==='instructions'?'Chiudi':'Annulla'}</button>{mode==='delete'&&<button className="delete-approve" disabled={busy} onClick={()=>act(onDelete)}>{busy?'Eliminazione…':'Sposta nel cestino'}</button>}{mode==='logout'&&<button className="publish-approve" disabled={busy} onClick={()=>act(onLogout)}>Esci</button>}</div></dialog></>;
}
