import {showAuthor,isEditorial,cleanSummary} from '../../lib/article-author';
import ArticleChecks from './ArticleChecks';
import {Fragment} from 'react';
import {orderedArticles} from '../../lib/editorial-topics';
import {orderedSectionArticles} from '../../lib/summary-sections';
import ReadingNavigation from './ReadingNavigation';
import SectionNavigation from './SectionNavigation';
import EditionRefresh from './EditionRefresh';
import EditionPicker from './EditionPicker';
import SectionEditButton from './SectionEditButton';
import BackToTop from './BackToTop';
import OutletWordmark from './OutletWordmark';
import EditionAnalysis from './EditionAnalysis';
import {tr,formatDate} from '../../lib/i18n';
export default function EditionView({body,lang='it',preview=false,onClip,privateClips=false,editorStatus=false,onEdit,categoryOrder,compactAnalysis=false,brandLogo,hideBrand=false}){
 body={...body,articles:categoryOrder?orderedSectionArticles(body.articles,categoryOrder):orderedArticles(body.articles)};
 const t=text=>tr(lang,text),count=n=>n+' '+t(n===1?'articolo':'articoli');
 const date=formatDate(lang,body.date,{weekday:'long',day:'numeric',month:'long',year:'numeric'}).toUpperCase();
 const categories=[...new Set(body.articles.map(a=>a.category).filter(Boolean))];
 return <div className="edition-view"><BackToTop lang={lang}/><ReadingNavigation lang={lang} articles={body.articles}/><header><div className="top">{!hideBrand&&<a className="brand" href="/">{brandLogo?<span className="jump-brand-lockup"><img className="jump-brand-logo" src={brandLogo} alt="Jump" width="90" height="49"/><span className="jump-brand-descriptor">PRESS</span></span>:<><i>JUMP</i> PRESS</>}</a>}<div className="edition">JUVENTUS · DAILY MEDIA INTELLIGENCE</div></div><div className="edition-date-line"><small>{date}</small><EditionPicker lang={lang} currentDate={body.date}/>{editorStatus&&<EditionRefresh/>}</div>{editorStatus&&<div className={`edition-status ${preview?'is-draft':'is-published'}`}><strong>{preview?'Bozza da verificare':'Pubblicata'}</strong><span>{preview?'Questa versione non è ancora visibile ai lettori.':'Questa versione è visibile ai lettori.'}</span></div>}{lang==='en'?<h1>Juventus <em>press review</em></h1>:<h1>Rassegna stampa <em>Juventus</em></h1>}<div className={onEdit?"editable-section editable-intro":undefined}><SectionEditButton onEdit={onEdit} section="intro" label="introduzione"/><p className="lead">{body.intro}</p></div><SectionNavigation lang={lang} articles={body.articles}/></header>
 <EditionAnalysis lang={lang} compact={compactAnalysis} onEdit={onEdit} body={body} onClip={onClip} privateClips={privateClips||preview}/>
 <div className="sectiontitle"><h2>{count(body.articles.length)}</h2></div><div className="articles">{body.articles.map((a,index)=><Fragment key={a.id}>{(index===0||body.articles[index-1].category!==a.category)&&<h2 className="article-group-heading" data-category={a.category}><span>{t(a.category)}</span><small>{count(body.articles.filter(item=>item.category===a.category).length)}</small><i aria-hidden="true"/></h2>}<article className={onEdit?"editable-section editable-article":undefined} key={a.id} id={'articolo-'+a.id} data-category={a.category} data-clip-id={a.clipId||undefined} data-private-clip={privateClips||preview?'true':undefined}>{compactAnalysis&&<span className="article-number-rail" aria-hidden="true">{String(index+1).padStart(2,'0')}</span>}<SectionEditButton onEdit={onEdit} section="article" articleId={a.id} label={'articolo: '+a.title}/>{compactAnalysis?(<div className="article-meta-line"><OutletWordmark name={a.outlet}/></div>): (<><div className="meta"><span>{a.category}</span>{a.category==='Editoriali'&&a.topic&&<small className="editorial-topic">{a.topic}</small>}<OutletWordmark name={a.outlet}/></div><div className="stars" aria-label={`Peso editoriale ${a.rating} su 5`}>{'★'.repeat(a.rating||0)}{'☆'.repeat(5-(a.rating||0))}</div></>)}<h2>{a.clipId?(privateClips||preview?<button className="article-title-link" type="button" onClick={()=>onClip?.(a.clipId)} title={t('Apri il ritaglio originale')}>{a.title}</button>:<a className="article-title-link" href={'/api/clips/'+a.clipId} target="_blank" rel="noreferrer" title={t('Apri il ritaglio originale')}>{a.title}</a>):a.title}</h2>{a.originalTitle&&a.originalTitle!==a.title&&<p className="article-original-title" lang="it"><span className="visually-hidden">{t('Titolo originale')}: </span>{a.originalTitle}</p>}{isEditorial(a)&&<div className="editorial-kicker"><span>{t('Editoriale')}</span>{a.author&&showAuthor(a)&&<em>{t('di')} {a.author}</em>}</div>}{a.author&&showAuthor(a)&&!isEditorial(a)&&<aside>{t('di')} {a.author}</aside>}<p>{cleanSummary(a)}</p>{preview&&<ArticleChecks article={a}/>}{!a.clipId&&preview&&<p>Ritaglio da associare prima della pubblicazione.</p>}</article></Fragment>)}</div><footer><b>JUMP PRESS</b> · {lang==='en'?'Juventus press review':'Rassegna Juventus'} · {formatDate(lang,body.date)}</footer></div>;
}
