import {Fragment} from 'react';
import {orderedArticles} from '../../lib/editorial-topics';
import ReadingNavigation from './ReadingNavigation';
import EditionRefresh from './EditionRefresh';
import SectionEditButton from './SectionEditButton';
import BackToTop from './BackToTop';
import OutletWordmark from './OutletWordmark';
import EditionAnalysis from './EditionAnalysis';
export default function EditionView({body,preview=false,onClip,privateClips=false,editorStatus=false,onEdit,categoryOrder,compactAnalysis=false,brandLogo,hideBrand=false}){
 body={...body,articles:categoryOrder?[...body.articles].sort((a,b)=>categoryOrder.indexOf(a.category)-categoryOrder.indexOf(b.category)):orderedArticles(body.articles)};
 const date=new Intl.DateTimeFormat('it-IT',{weekday:'long',day:'numeric',month:'long',year:'numeric',timeZone:'UTC'}).format(new Date(body.date+'T12:00:00Z')).toUpperCase();
 const categories=[...new Set(body.articles.map(a=>a.category).filter(Boolean))];
 return <div className="edition-view"><BackToTop/><ReadingNavigation articles={body.articles}/><header><div className="top">{!hideBrand&&<a className="brand" href="/">{brandLogo?<span className="jump-brand-lockup"><img className="jump-brand-logo" src={brandLogo} alt="Jump" width="90" height="49"/><span className="jump-brand-descriptor">PRESS</span></span>:<><i>JUMP</i> PRESS</>}</a>}<div className="edition">JUVENTUS · DAILY MEDIA INTELLIGENCE</div></div><div className="edition-date-line"><small>{date}</small>{editorStatus&&<EditionRefresh/>}</div>{editorStatus&&<div className={`edition-status ${preview?'is-draft':'is-published'}`}><strong>{preview?'Bozza da verificare':'Pubblicata'}</strong><span>{preview?'Questa versione non è ancora visibile ai lettori.':'Questa versione è visibile ai lettori.'}</span></div>}<h1>Rassegna stampa <em>Juventus</em></h1><div className={onEdit?"editable-section editable-intro":undefined}><SectionEditButton onEdit={onEdit} section="intro" label="introduzione"/><p className="lead">{body.intro}</p></div>{categories.length>1&&<nav className="edition-jump-nav" aria-label="Vai agli articoli per tema"><span>Vai a</span>{categories.map(category=><a key={category} data-edition-jump="true" href={'#articolo-'+body.articles.find(a=>a.category===category).id}>{category}</a>)}</nav>}</header>
 <EditionAnalysis compact={compactAnalysis} onEdit={onEdit} body={body} onClip={onClip} privateClips={privateClips||preview}/>
 <div className="sectiontitle"><small>RASSEGNA SELEZIONATA</small><h2>{body.articles.length} {body.articles.length===1?'articolo':'articoli'}</h2></div><div className="articles">{body.articles.map((a,index)=><Fragment key={a.id}>{(index===0||body.articles[index-1].category!==a.category)&&<h2 className="article-group-heading" data-category={a.category}><span>{a.category}</span><small>{body.articles.filter(item=>item.category===a.category).length} {body.articles.filter(item=>item.category===a.category).length===1?'articolo':'articoli'}</small><i aria-hidden="true"/></h2>}<article className={onEdit?"editable-section editable-article":undefined} key={a.id} id={'articolo-'+a.id} data-category={a.category} data-clip-id={a.clipId||undefined} data-private-clip={privateClips||preview?'true':undefined}>{compactAnalysis&&<span className="article-number-rail" aria-hidden="true">{String(index+1).padStart(2,'0')}</span>}<SectionEditButton onEdit={onEdit} section="article" articleId={a.id} label={'articolo: '+a.title}/>{compactAnalysis?(<div className="article-meta-line"><OutletWordmark name={a.outlet}/><div className="article-relevance" aria-label={`Rilevanza ${a.rating} su 5`} title={`Rilevanza editoriale: ${a.rating} su 5`}><span aria-hidden="true">Rilevanza</span><span className="article-relevance-bars" aria-hidden="true">{[1,2,3,4,5].map(n=><i key={n} className={n<=a.rating?"is-filled":""}/>)}</span></div></div>): (<><div className="meta"><span>{a.category}</span>{a.category==='Editoriali'&&a.topic&&<small className="editorial-topic">{a.topic}</small>}<OutletWordmark name={a.outlet}/></div><div className="stars" aria-label={`Peso editoriale ${a.rating} su 5`}>{'★'.repeat(a.rating||0)}{'☆'.repeat(5-(a.rating||0))}</div></>)}<h2>{a.clipId?(privateClips||preview?<button className="article-title-link" type="button" onClick={()=>onClip?.(a.clipId)} title="Apri il ritaglio originale">{a.title}</button>:<a className="article-title-link" href={'/api/clips/'+a.clipId} target="_blank" rel="noreferrer" title="Apri il ritaglio originale">{a.title}</a>):a.title}</h2>{a.author&&<aside>di {a.author}</aside>}<p>{a.summary}</p>{!a.clipId&&preview&&<p>Ritaglio da associare prima della pubblicazione.</p>}</article></Fragment>)}</div><footer><b>JUMP PRESS</b> · Rassegna Juventus · {body.date}</footer></div>;
}
