import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import {MemoryStore} from './helpers.mjs';import {claimRun,recordReadActivity,readRun,LEASE_MS,updateRun} from '../lib/automation-runs.js';import {saveDraft} from '../lib/editor-service.js';import {newEdition} from '../lib/schema.js';
const date='2026-09-18',url='https://rassegna.dominiocliente.it/Areas/Rassegna/Elab/CheckedDownload.aspx?nome_file=PP_RAS_1626482_20260918_16377886.pdf';
async function fixture(enabled=true){let time=1800000000000;const ctx={activityRenewal:enabled,role:'publisher',user:{id:'editor'},store:new MemoryStore(),now:()=>time},advance=ms=>time+=ms;const job=await claimRun(ctx,{date,url,requestId:randomUUID()}),importId=randomUUID();const h=await ctx.store.begin(),row=await ctx.store.read('automation/runs/'+date+'.json',h);await ctx.store.commit({['automation/runs/'+date+'.json']:{...row,checkpoint:{importId,nextPage:41},phase:'reading'}},h);return {ctx,job,importId,advance};}
test('valid activity renews only after threshold and preserves factual checkpoints and phase times',async()=>{const {ctx,job,importId,advance}=await fixture();const before=await readRun(ctx,date),v=ctx.store.version;await recordReadActivity(ctx,job.run,importId);assert.equal(ctx.store.version,v);advance(120001);await recordReadActivity(ctx,job.run,importId);const after=await readRun(ctx,date);assert.equal(after.leaseUntil,before.leaseUntil+120001);assert.deepEqual(after.checkpoint,before.checkpoint);assert.equal(after.phase,before.phase);assert.deepEqual(after.timings,before.timings);advance(LEASE_MS+1);await assert.rejects(recordReadActivity(ctx,job.run,importId),e=>e.status===409);});
test('foreign source, foreign owner, expired generation and completed work cannot renew',async()=>{const {ctx,job,importId,advance}=await fixture();advance(120001);await assert.rejects(recordReadActivity(ctx,job.run,randomUUID()),e=>e.status===409);await assert.rejects(recordReadActivity({...ctx,user:{id:'other'}},job.run,importId),e=>e.status===409);await assert.rejects(recordReadActivity(ctx,{...job.run,generation:2},importId),e=>e.status===409);await updateRun(ctx,{run:job.run,phase:'reading',status:'failed'});await assert.rejects(recordReadActivity(ctx,job.run,importId),e=>e.status===409);});
test('save renews atomically without changing the draft version contract; switch off preserves old behavior',async()=>{for(const enabled of [true,false]){const {ctx,job,advance}=await fixture(enabled);const before=await readRun(ctx,date);advance(180000);const v=ctx.store.version;const draft=await saveDraft({...ctx,automation:job.run},job.draftId,0,newEdition(date));assert.equal(draft.version,1);assert.equal(ctx.store.version,v+1);assert.equal((await readRun(ctx,date)).leaseUntil,before.leaseUntil+(enabled?180000:0));await assert.rejects(saveDraft({...ctx,automation:job.run},job.draftId,0,newEdition(date)),e=>e.status===409);}});
test('monitor reads never renew and concurrent renewal conflicts cannot overwrite progress',async()=>{const {ctx,job,importId,advance}=await fixture();advance(180000);const v=ctx.store.version;await readRun(ctx,date);assert.equal(ctx.store.version,v);const results=await Promise.allSettled([recordReadActivity(ctx,job.run,importId),recordReadActivity(ctx,job.run,importId)]);assert(results.some(x=>x.status==='fulfilled'));for(const r of results)if(r.status==='rejected')assert.equal(r.reason.status,409);assert.equal((await readRun(ctx,date)).checkpoint.nextPage,41);});
import {Client} from '@modelcontextprotocol/sdk/client/index.js';import {InMemoryTransport} from '@modelcontextprotocol/sdk/inMemory.js';import {createEditorialMcp} from '../lib/mcp-server.js';
test('MCP renews successful source reads only, never failed reads or monitoring',async()=>{const {ctx,job,importId,advance}=await fixture();let fail=false;ctx.blobs={readText:async()=>{if(fail)throw Object.assign(Error('unavailable'),{status:503});return {pages:[{page:1,text:'original source'}]};}};await ctx.store.commit({['imports/'+importId+'.json']:{id:importId,date,status:'ready',pageCount:1,textPath:'test'}},await ctx.store.begin());const server=createEditorialMcp(ctx),client=new Client({name:'activity-test',version:'1'}),[a,b]=InMemoryTransport.createLinkedPair();try{await server.connect(a);await client.connect(b);advance(180000);let before=await readRun(ctx,date);const read=await client.callTool({name:'read_source_text',arguments:{run:job.run,importId,startPage:1,endPage:1}});assert(!read.isError);assert.equal((await readRun(ctx,date)).leaseUntil,before.leaseUntil+180000);advance(180000);before=await readRun(ctx,date);fail=true;assert((await client.callTool({name:'read_source_text',arguments:{run:job.run,importId,startPage:1,endPage:1}})).isError);await client.callTool({name:'read_automation_run',arguments:{date}});assert.equal((await readRun(ctx,date)).leaseUntil,before.leaseUntil);}finally{await client.close();await server.close();}});
