import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {MemoryStore} from './helpers.mjs';
import {newEdition} from '../lib/schema.js';
import {saveDraft,getDraft} from '../lib/editor-service.js';
import {newReview,reviewPath,readReview,claimReview,saveReview,finishReview,notifyReady} from '../lib/editorial-review.js';
import {automationStore} from '../lib/automation-runs.js';
async function fixture(){let time=1800000000000;const ctx={store:new MemoryStore(),role:'publisher',user:{id:'editor'},now:()=>time,advance:n=>time+=n};const a={id:randomUUID(),title:'Una notizia',category:'Sport',outlet:'Testata',summary:'Testo originale',pages:[1]};const draft=await saveDraft(ctx,randomUUID(),0,{...newEdition('2026-10-08'),intro:'Introduzione',articles:[a]});await ctx.store.commit({[reviewPath(draft.id)]:newReview(draft,time)},await ctx.store.begin());return {ctx,draft,a};}
const start=x=>claimReview(x.ctx,{draftId:x.draft.id,requestId:randomUUID()});
const save=(x,job,extra={})=>saveReview(x.ctx,{review:job.review,version:job.version,operationId:randomUUID(),...extra});
test('one worker owns review; expired work can resume and old tokens cannot save',async()=>{const x=await fixture(),requestId=randomUUID(),args={draftId:x.draft.id,requestId};const first=await claimReview(x.ctx,args);assert(first.acquired);assert.deepEqual((await claimReview(x.ctx,args)).review,first.review);assert.equal((await start(x)).reason,'in_progress');x.ctx.advance(21*60000);assert.equal((await readReview(x.ctx,x.draft.id)).status,'interrupted');const next=await start(x);assert(next.acquired);await assert.rejects(save(x,first,{corrections:[{id:x.a.id,changes:{summary:'Vecchio'}}]}),e=>e.stop);assert.equal((await getDraft(x.ctx,x.draft.id)).body.articles[0].summary,'Testo originale');});
test('partial edits are idempotent and never replace unrelated content',async()=>{const x=await fixture(),job=await start(x),operationId=randomUUID(),args={review:job.review,version:job.version,operationId,corrections:[{id:x.a.id,changes:{summary:'Sintesi corretta',editorialNote:''}}]};const result=await saveReview(x.ctx,args);const again=await saveReview(x.ctx,args);assert(again.alreadySaved);assert.equal(again.version,result.version);const d=await getDraft(x.ctx,x.draft.id);assert.equal(d.body.intro,'Introduzione');assert.equal(d.body.articles[0].summary,'Sintesi corretta');assert.equal(d.body.articles[0].title,'Una notizia');assert.deepEqual((await readReview(x.ctx,x.draft.id)).protectedFields,{});});
test('human edits remain protected after rereading; other article fields can be corrected',async()=>{const x=await fixture(),job=await start(x);const human=await saveDraft(x.ctx,x.draft.id,job.version,{...x.draft.body,articles:[{...x.a,summary:'Scritto dal giornalista'}]});await assert.rejects(save(x,job,{corrections:[{id:x.a.id,changes:{summary:'Obsoleto'}}]}),e=>e.status===409);job.version=human.version;await assert.rejects(save(x,job,{corrections:[{id:x.a.id,changes:{summary:'Sovrascrive'}}]}),e=>e.status===409);const d=await save(x,job,{corrections:[{id:x.a.id,changes:{author:'Autore verificato'}}]});assert(d.version>human.version);assert.equal((await getDraft(x.ctx,x.draft.id)).body.articles[0].summary,'Scritto dal giornalista');assert((await readReview(x.ctx,x.draft.id)).protectedFields[x.a.id].includes('summary'));});
test('review cannot remove main selection or reserves or add more than two in multiple saves',async()=>{const x=await fixture(),job=await start(x),add=n=>({...x.a,id:randomUUID(),title:'Riserva '+n,reserveReason:'Tema utile'});let r=await save(x,job,{additions:[add(1)]});job.version=r.version;r=await save(x,job,{additions:[add(2)]});job.version=r.version;await assert.rejects(save(x,job,{additions:[add(3)]}),e=>e.status===422);const d=await getDraft(x.ctx,x.draft.id);assert.equal(d.body.reserveArticles.length,2);await assert.rejects(saveDraft({...x.ctx,editorialReview:job.review},d.id,d.version,{...d.body,articles:[]}),e=>e.status===403);await assert.rejects(saveDraft({...x.ctx,editorialReview:job.review},d.id,d.version,{...d.body,reserveArticles:[]}),e=>e.status===403);});
test('published and removed drafts fence the worker; closed revisions cannot be written',async()=>{const x=await fixture(),job=await start(x),r=x.ctx.store;await r.commit({'index.json':{...r.files['index.json'],published:[{draft_id:x.draft.id}]}},await r.begin());await assert.rejects(save(x,job),e=>e.stop);await assert.rejects(finishReview(x.ctx,{review:job.review,version:job.version,completed:true,report:'Finito'}),e=>e.stop);const y=await fixture(),run=await start(y);const row=y.ctx.store.files['drafts/'+y.draft.id+'.json'];await automationStore(y.ctx).commit({['drafts/'+row.id+'.json']:{...row,deletedAt:'now'}},await y.ctx.store.begin());await assert.rejects(save(y,run),e=>e.stop);});
test('completion checks current version, is idempotent and marks subsequent human edits',async()=>{const x=await fixture(),job=await start(x);await assert.rejects(finishReview(x.ctx,{review:job.review,version:999,completed:true,report:'Finito'}),e=>e.status===409);const args={review:job.review,version:job.version,completed:true,report:'Controllo concluso, nessuna aggiunta.'};assert.equal((await finishReview(x.ctx,args)).status,'completed');assert.equal((await finishReview(x.ctx,args)).status,'completed');assert.equal((await start(x)).reason,'completed');await assert.rejects(save(x,job),e=>e.stop);await saveDraft(x.ctx,x.draft.id,job.version,{...x.draft.body,intro:'Cappello aggiornato'});assert.equal((await readReview(x.ctx,x.draft.id)).modifiedAfterReview,true);});
test('read errors remain errors; failed notifications stay visible and sent ones do not repeat',async()=>{const x=await fixture();await assert.rejects(readReview({...x.ctx,store:{begin:async()=>{throw Error('offline');}}},x.draft.id),/offline/);await assert.rejects(readReview({...x.ctx,role:'anonymous'},x.draft.id),e=>e.status===403);await notifyReady({...x.ctx,notifyReady:async()=>{throw Object.assign(Error('rejected'),{status:503});}},x.draft.id);assert.equal((await readReview(x.ctx,x.draft.id)).notification.status,'failed');let count=0;const c={...x.ctx,notifyReady:async()=>{count++;return {status:'sent'};}};await notifyReady(c,x.draft.id);await notifyReady(c,x.draft.id);assert.equal(count,1);});
test('uncertain SMTP delivery is never retried automatically',async()=>{const x=await fixture();let count=0;const c={...x.ctx,notifyReady:async()=>{count++;throw Object.assign(Error('unknown'),{status:409});}};await notifyReady(c,x.draft.id);await notifyReady(c,x.draft.id);assert.equal(count,1);assert.equal((await readReview(x.ctx,x.draft.id)).notification.status,'uncertain');});
