import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {PDFDocument,StandardFonts} from 'pdf-lib';
import {Client} from '@modelcontextprotocol/sdk/client/index.js';
import {InMemoryTransport} from '@modelcontextprotocol/sdk/inMemory.js';
import {createEditorialMcp} from '../lib/mcp-server.js';
import {MemoryStore} from './helpers.mjs';
import {extractSourceText} from '../lib/source-pdf.js';
async function session(ctx){const server=createEditorialMcp(ctx),client=new Client({name:'manual-test',version:'1'}),[a,b]=InMemoryTransport.createLinkedPair();await server.connect(a);await client.connect(b);return {client,close:async()=>{await client.close();await server.close();}};}
for(const role of ['producer','editor','publisher'])test('manual MCP respects authenticated role '+role,async()=>{const s=await session({role,store:new MemoryStore(),user:{id:'editor'}});try{const {tools}=await s.client.listTools();assert(tools.some(t=>t.name==='read_manual_source'));for(const name of ['prepare_manual_source','finalize_manual_source','notify_manual_source'])assert.equal(tools.some(t=>t.name===name),role!=='producer');}finally{await s.close();}});
test('manual MCP prepare, immutable uploads, finalization and idempotent notification retain one private source',async()=>{const files=new Map(),ctx={role:'publisher',user:{id:'editor'},store:new MemoryStore(),extractSourceText};ctx.blobs={uploadLink:async p=>'https://files.invalid/'+p,read:async p=>{if(!files.has(p))throw Object.assign(Error('missing'),{status:404});return files.get(p);},readOriginal:async p=>{if(!files.has(p))throw Object.assign(Error('missing'),{status:404});return files.get(p);},writeOriginal:async(p,b)=>files.set(p,b),readText:async p=>{if(!files.has(p))throw Object.assign(Error('missing'),{status:404});return files.get(p);},writeText:async(p,x)=>files.set(p,x)};let sent=0;ctx.notifySource=async()=>{sent++;return {status:'sent',acceptedAt:new Date().toISOString()};};const doc=await PDFDocument.create(),font=await doc.embedFont(StandardFonts.Helvetica);doc.addPage().drawText('Notizia reale di esempio per estrazione del testo nel test isolato',{font,x:20,y:700});const bytes=Buffer.from(await doc.save()),id=randomUUID(),input={id,date:'2026-10-02',files:[{name:'Prima.pdf',size:bytes.length},{name:'Seconda.pdf',size:bytes.length}]},s=await session(ctx),call=async(name,args)=>s.client.callTool({name,arguments:args});try{assert.equal(JSON.parse((await call('read_manual_source',{date:input.date})).content[0].text),null);const prepared=await call('prepare_manual_source',{input});assert(!prepared.isError);const uploads=JSON.parse(prepared.content[0].text).uploads;assert.equal(uploads.length,2);assert.equal((await call('notify_manual_source',{importId:id,confirmation:'INVIA_RASSEGNA'})).isError,true);for(const u of uploads)files.set(u.path,bytes);assert(!(await call('finalize_manual_source',{importId:id})).isError);let state=JSON.parse((await call('read_manual_source',{importId:id})).content[0].text);assert.equal(state.status,'ready');assert.equal(state.pageCount,2);assert(!(await call('notify_manual_source',{importId:id,confirmation:'INVIA_RASSEGNA'})).isError);await call('notify_manual_source',{importId:id,confirmation:'INVIA_RASSEGNA'});assert.equal(sent,1);assert.equal(ctx.store.files['index.json'].drafts.length,0);assert.equal((await call('prepare_manual_source',{input:{...input,id:randomUUID()}})).isError,true);}finally{await s.close();}});
test('manual MCP refuses source preparation and mail from scheduled context',async()=>{const s=await session({role:'publisher',store:new MemoryStore(),user:{id:'editor'},automation:{runId:randomUUID()}});try{const response=await s.client.callTool({name:'prepare_manual_source',arguments:{input:{id:randomUUID(),date:'2026-10-02',files:[{name:'Sezione.pdf',size:1}]}}});assert(response.isError);assert.equal(JSON.parse(response.content[0].text).status,403);const mail=await s.client.callTool({name:'notify_manual_source',arguments:{importId:randomUUID(),confirmation:'INVIA_RASSEGNA'}});assert(mail.isError);assert.equal(JSON.parse(mail.content[0].text).status,403);}finally{await s.close();}});
