import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {PDFDocument,StandardFonts} from 'pdf-lib';
import {MemoryStore} from './helpers.mjs';
import {prepareManualSource,finalizeManualSource,manualState} from '../lib/manual-source.js';
import {notifyManualSource} from '../lib/source-notification.js';
import {claimRun,updateRun,assertRun,recordActivity} from '../lib/automation-runs.js';
import {readImportTextBatch,importPdf} from '../lib/source-service.js';
import {extractSourceText} from '../lib/source-pdf.js';
const date='2026-10-02',url='https://rassegna.dominiocliente.it/Areas/Rassegna/Elab/CheckedDownload.aspx?nome_file=PP_RAS_1626482_20261002_16440459.pdf';
async function fixture(){const files=new Map(),store=new MemoryStore(),docs=[];for(const name of ['Prima squadra','Women']){const d=await PDFDocument.create(),font=await d.embedFont(StandardFonts.Helvetica);d.addPage().drawText(name+' Juventus - notizia verificabile della sezione selezionata',{font,size:12,x:20,y:700});docs.push(Buffer.from(await d.save()));}
 const get=async p=>{if(!files.has(p))throw Object.assign(Error('Assente'),{status:404});return files.get(p);};
 const put=async(p,v)=>{if(files.has(p))throw Object.assign(Error('Presente'),{status:409});files.set(p,v);};
 return {ctx:{role:'publisher',user:{id:'editor'},store,blobs:{read:get,readOriginal:get,writeOriginal:put,readText:get,writeText:put,uploadLink:async p=>'https://files.invalid/'+p},extractSourceText},files,docs,input:{id:randomUUID(),date,files:docs.map((b,i)=>({name:'Sezione '+i+'.pdf',size:b.length}))}};
}
async function ready(f){const p=await prepareManualSource(f.ctx,f.input);p.uploads.forEach((u,i)=>f.files.set(u.path,f.docs[i]));await finalizeManualSource(f.ctx,f.input.id);return f.input.id;}
test('private sections become one source with exact page order; no draft is invented',async()=>{const f=await fixture(),id=await ready(f),state=await manualState(f.ctx,id);assert.equal(state.pageCount,2);assert.deepEqual(state.sections.map(s=>[s.startPage,s.endPage]),[[1,1],[2,2]]);const text=await readImportTextBatch(f.ctx,id,1);assert.match(text.pages[0].text,/Prima squadra/);assert.match(text.pages[1].text,/Women/);assert.equal(f.ctx.store.files['index.json'].drafts.length,0);assert.equal((await finalizeManualSource(f.ctx,id)).status,'ready');});
test('roles, immutable metadata, running jobs and duplicate dates fence manual uploads',async()=>{const f=await fixture();await assert.rejects(prepareManualSource({...f.ctx,role:'producer'},f.input),e=>e.status===403);await prepareManualSource(f.ctx,f.input);await assert.rejects(prepareManualSource(f.ctx,{...f.input,id:randomUUID()}),e=>e.status===409);await assert.rejects(prepareManualSource(f.ctx,{...f.input,files:[{name:'Different.pdf',size:1}]}),e=>e.status===409);const g=await fixture();await claimRun(g.ctx,{date,url,requestId:randomUUID()});await assert.rejects(prepareManualSource(g.ctx,g.input),e=>e.status===409);});
test('incomplete upload preserves source and resumes after the missing PDF arrives',async()=>{const f=await fixture(),p=await prepareManualSource(f.ctx,f.input);f.files.set(p.uploads[0].path,f.docs[0]);await assert.rejects(finalizeManualSource(f.ctx,f.input.id));assert.equal((await manualState(f.ctx,f.input.id)).status,'failed');f.files.set(p.uploads[1].path,f.docs[1]);assert.equal((await finalizeManualSource(f.ctx,f.input.id)).status,'ready');});
test('failed Ecostampa run can adopt the editor-selected manual source; old worker is fenced',async()=>{const f=await fixture(),old=await claimRun(f.ctx,{date,url,requestId:randomUUID()});await updateRun(f.ctx,{run:old.run,phase:'import',status:'failed',retryable:false});const id=await ready(f);assert.equal((await claimRun(f.ctx,{date,url,requestId:randomUUID()})).reason,'manual_source_active');await assert.rejects(importPdf(f.ctx,{date,url}),e=>e.status===409);const next=await claimRun(f.ctx,{date,importId:id,requestId:randomUUID()});assert(next.acquired);assert.equal(next.checkpoint.importId,id);assert.equal(next.phase,'reading');await assert.rejects(assertRun(f.ctx,old.run),e=>e.stop===true);await recordActivity(f.ctx,{run:next.run,importId:id,pages:[1,2]});const row=f.ctx.store.files['automation/runs/'+date+'.json'];assert.equal(row.checkpoint.nextPage,3);assert(f.ctx.store.files['automation/manual-recovery/'+date+'/'+old.run.runId+'.json']);});
test('manual claim rejects another date, source URL plus ID, and source not ready',async()=>{const f=await fixture();await prepareManualSource(f.ctx,f.input);await assert.rejects(claimRun(f.ctx,{date,importId:f.input.id,requestId:randomUUID()}),e=>e.status===422);await ready(f);await assert.rejects(claimRun(f.ctx,{date:'2026-10-03',importId:f.input.id,requestId:randomUUID()}),e=>e.status===422);await assert.rejects(claimRun(f.ctx,{date,url,importId:f.input.id,requestId:randomUUID()}),e=>e.status===422);});
test('notification only sends ready source identifiers; duplicate clicks do not resend',async()=>{const f=await fixture(),id=await ready(f);let count=0;f.ctx.notifySource=async x=>{count++;assert.deepEqual(x,{importId:id,date});return {status:'sent',acceptedAt:'2026-10-02T10:00:00Z'};};await notifyManualSource(f.ctx,id);await notifyManualSource(f.ctx,id);assert.equal(count,1);assert.equal((await manualState(f.ctx,id)).notification.status,'sent');});
test('notification service failure preserves PDFs and never reports success',async()=>{const f=await fixture(),id=await ready(f);f.ctx.notifySource=async()=>{throw Object.assign(Error('Esito incerto'),{status:409});};await assert.rejects(notifyManualSource(f.ctx,id),e=>e.status===409);assert.equal((await manualState(f.ctx,id)).status,'ready');assert.equal((await manualState(f.ctx,id)).notification,null);});
test('missing mail configuration does not destroy uploads or claim success',async()=>{const f=await fixture(),id=await ready(f);await assert.rejects(notifyManualSource(f.ctx,id),e=>e.status===422);assert.equal((await manualState(f.ctx,id)).notification,null);assert.equal((await manualState(f.ctx,id)).status,'ready');});

test('more than twenty sections retain their order and page numbering',async()=>{const f=await fixture();f.docs=Array.from({length:21},(_,i)=>f.docs[i%2]);f.input.files=f.docs.map((b,i)=>({name:'Sezione '+i+'.pdf',size:b.length}));const id=await ready(f),state=await manualState(f.ctx,id);assert.equal(state.pageCount,21);assert.equal(state.sections.length,21);assert.deepEqual(state.sections.map(s=>s.startPage),Array.from({length:21},(_,i)=>i+1));});
