import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm,readFile,writeFile,mkdir} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {randomUUID} from 'node:crypto';
import {sendSourceMail,mailConfig} from '../services/jump-press-files/source-mail.mjs';
const env={CONTACT_SMTP_HOST:'smtp.invalid',CONTACT_SMTP_USER:'editor@test.invalid',CONTACT_SMTP_PASS:'test-only',JUMP_MAIL_TO:'recipient@test.invalid'};
async function fixture(fn){const root=await mkdtemp(join(tmpdir(),'jp-mail-'));try{await fn({root,env,input:{importId:randomUUID(),date:'2026-10-02'}});}finally{await rm(root,{recursive:true,force:true});}}
test('SMTP envelope is fixed, private and duplicate requests reuse durable receipt',()=>fixture(async x=>{let count=0;const sendMail=async m=>{count++;assert.equal(m.to,env.JUMP_MAIL_TO);assert.match(m.subject,/^\[Jump Press\] Fonte manuale pronta/);assert.match(m.text,new RegExp(x.input.importId));assert(!m.attachments);assert(!m.text.includes(env.CONTACT_SMTP_PASS));assert(!m.text.includes('https://'));return {accepted:[m.to]};};const first=await sendSourceMail({...x,sendMail});assert.deepEqual(await sendSourceMail({...x,sendMail}),first);assert.equal(count,1);}));
test('concurrent requests never send a second message',()=>fixture(async x=>{let release;const started=new Promise(r=>release=r);let finish;const pending=new Promise(r=>finish=r);const first=sendSourceMail({...x,sendMail:async m=>{release();await pending;return {accepted:[m.to]};}});await started;await assert.rejects(sendSourceMail({...x,sendMail:()=>assert.fail()}),e=>e.status===409);finish();await first;}));
test('uncertain SMTP acceptance blocks blind retries while definite rejection can retry',()=>fixture(async x=>{await assert.rejects(sendSourceMail({...x,sendMail:async()=>{throw Object.assign(Error('Connection lost'),{command:'DATA'});}}),e=>e.status===409);await assert.rejects(sendSourceMail({...x,sendMail:()=>assert.fail()}),e=>e.status===409);const receipt=JSON.parse(await readFile(join(x.root,'.notifications',x.input.importId+'.json'),'utf8'));assert.equal(receipt.status,'unknown');}));
test('retry after rejection preserves original recipient despite configuration change',()=>fixture(async x=>{await assert.rejects(sendSourceMail({...x,sendMail:async()=>{throw Object.assign(Error('Rejected'),{responseCode:550});}}),e=>e.status===503);await sendSourceMail({...x,env:{...env,JUMP_MAIL_TO:'changed@test.invalid'},sendMail:async m=>{assert.equal(m.to,env.JUMP_MAIL_TO);return {accepted:[m.to]};}});}));
test('corrupt receipt is unavailable, never treated as absent',()=>fixture(async x=>{await mkdir(join(x.root,'.notifications'));await writeFile(join(x.root,'.notifications',x.input.importId+'.json'),'{broken');await assert.rejects(sendSourceMail({...x,sendMail:()=>assert.fail()}),e=>e.status===503);}));
test('SMTP requires TLS and input cannot choose recipients or escape storage',()=>fixture(async x=>{assert.equal(mailConfig(env).options.requireTLS,true);assert.equal(mailConfig({...env,CONTACT_SMTP_PORT:'465'}).options.secure,true);assert.throws(()=>mailConfig({...env,CONTACT_SMTP_PORT:'25'}),e=>e.status===422);await assert.rejects(sendSourceMail({...x,input:{...x.input,importId:'../../escape'},sendMail:()=>assert.fail()}),e=>e.status===400);await sendSourceMail({...x,input:{...x.input,to:'attacker@test.invalid'},sendMail:async m=>{assert.equal(m.to,env.JUMP_MAIL_TO);return {accepted:[m.to]};}});}));
