const articles = [
  {cat:'Editoriali', outlet:'Libero Quotidiano', title:'Allegri già al bivio a Napoli Spalletti cerca nuovi leader', author:'Claudio Savelli', summary:'Savelli legge l’emergenza come un banco di prova per la capacità degli allenatori di rigenerare uomini e gerarchie. Alla Juventus l’assenza di Locatelli e Thuram sposta responsabilità su Bremer e soprattutto su Douglas Luiz e Koopmeiners. Spalletti vuole trasformarli in riferimenti e rifiuta la cultura degli alibi.', pages:'56-57', stars:5},
  {cat:'Editoriali', outlet:'La Gazzetta dello Sport', title:'IL MILAN ANCORA CONFUSO E MODRIC È UN PROBLEMA. NAPOLI E JUVE, VINCERE O...', author:'Sebastiano Vernazza', summary:'Vernazza divide le big tra chi possiede già un’identità riconoscibile e chi appare ancora poco definito. Sulla Juventus parla di una squadra ancora sgranata e assegna a Spalletti una responsabilità maggiore rispetto ad altri tecnici, perché lavora da più tempo sulla propria squadra. A Sassuolo il risultato pesa.', pages:'50-51', stars:5},
  {cat:'Juventus', outlet:'La Gazzetta dello Sport', title:'JUVE Spalletti ci prova con sette nuovi «Ma niente alibi»', author:'', summary:'L’emergenza accelera la trasformazione della Juventus: contro il Sassuolo possono esserci sette titolari nuovi rispetto alla squadra della scorsa stagione. Douglas Luiz e Koopmeiners sono destinati a formare la coppia centrale, Nico Gonzalez avrà compiti mobili, Kolo Muani resta il riferimento offensivo e Alajbegovic è tra i candidati per partire dall’inizio.', pages:'15-18', stars:5},
  {cat:'Juventus', outlet:'Tuttosport', title:'Spalletti non vuole alibi «Juve, vai oltre i ko!»', author:'', summary:'Spalletti chiude il capitolo delle giustificazioni: la Juventus deve giocare all’altezza della propria storia indipendentemente dagli assenti. Kolo Muani si è presentato alla Continassa con largo anticipo; Koopmeiners viene descritto come più libero e sciolto, mentre Douglas Luiz è definito dal tecnico una certezza del calcio. Sarr torna a disposizione.', pages:'34-37', stars:5},
  {cat:'Juventus', outlet:'La Stampa', title:'Juventus, la voglia matta di Kolo Muani', author:'', summary:'Kolo Muani cerca ancora il primo gol della nuova stagione bianconera e risponde alle difficoltà aumentando il lavoro. Spalletti racconta di averlo trovato alla Continassa diverse ore prima del previsto, interpretandolo come un segnale della sua voglia di incidere. Resta possibile anche l’esperimento con Kolo e Woltemade insieme.', pages:'25-26', stars:4},
  {cat:'Juventus', outlet:'Corriere dello Sport Stadio', title:'Sua altezza Woltemade', author:'', summary:'Spalletti valuta l’impiego del tedesco insieme a Kolo Muani: i suoi 198 centimetri si accompagnano a qualità tecniche che gli permettono di giocare sia da riferimento offensivo sia alle spalle della punta. Il tecnico considera ormai completato il suo inserimento. Woltemade spiega di potersi muovere da numero 10 e di essere intercambiabile con Kolo.', pages:'42-44', stars:4},
  {cat:'Juventus', outlet:'Tuttosport', title:'Provaci ancora Koop. Sarà il faro di Spalletti', author:'', summary:'Con Locatelli e Thuram fuori, Sarr appena recuperato e McKennie indisponibile, Koopmeiners è chiamato a prendersi una responsabilità maggiore accanto a Douglas Luiz. Dopo un’estate nella quale anche una sua uscita era stata presa in considerazione, l’olandese ha voluto restare e ora può ritrovare una nuova centralità.', pages:'59', stars:4},
  {cat:'Juventus', outlet:'QN Sport', title:'Spalletti deve reinventare la Signora Chance Sarr', author:'', summary:'Le assenze costringono Spalletti ad accelerare l’utilizzo dei nuovi: Sarr è l’unico recuperato per la trasferta e può diventare una soluzione importante in mezzo. Alajbegovic è candidato sulla sinistra, Woltemade dovrebbe trovare spazio e resta possibile la coppia con Kolo Muani. Koopmeiners e Douglas Luiz sono la soluzione più probabile a centrocampo.', pages:'29-30', stars:4},
  {cat:'Intervista', outlet:'Tuttosport', title:'«Juve, serve tempo per vincere di nuovo»', author:'', summary:'Massimo Mauro ritiene che per ricostruire una Juventus abituata a vincere servirà tempo, anche per le conseguenze delle precedenti gestioni societarie. La priorità deve essere ricreare uno spogliatoio forte e con un’identità marcata, possibilmente italiana: cita come modello Buffon, Chiellini, Bonucci, Marchisio, Pirlo e Barzagli.', pages:'38-39', stars:4},
  {cat:'Juventus', outlet:'Tuttosport', title:'Straordinari per Conceição. Kolo ci riprova', author:'', summary:'Spalletti prepara un turnover molto limitato: Conceição, indicato tra i giocatori più in forma, va ancora verso una maglia da titolare. Kolo Muani resta favorito al centro dell’attacco, ma Woltemade può trovare spazio anche insieme al francese. Sarr torna convocabile, mentre McKennie non è ancora pronto.', pages:'58', stars:3},
  {cat:'Mercato', outlet:'Tuttosport', title:'Milik-Juve: prove d’addio. Piace a due club sauditi', author:'', summary:'Tuttosport segnala nuove prove di separazione tra Milik e la Juventus e riferisce l’interesse di due club sauditi. La scheda resta volutamente limitata alle informazioni verificabili dal titolo, perché la pagina 40 non restituisce testo estraibile sufficiente per aggiungere in sicurezza nomi, cifre o formule.', pages:'40', stars:4},
  {cat:'Mercato', outlet:'Tuttosport', title:'Amore & altri rimedi. Juve, riecco Berardi', author:'', summary:'Il pezzo ricostruisce il lunghissimo intreccio tra Berardi e la Juventus: dalla comproprietà del 2013 al mancato approdo definitivo, fino all’estate 2023, quando l’accordo con il giocatore non bastò perché il Sassuolo chiedeva 30 milioni. Oggi Carnevali è alla Juventus e Berardi resta neroverde, pronto a ritrovare i bianconeri da avversario.', pages:'41', stars:3},
  {cat:'Juventus Youth', outlet:'Tuttosport', title:'Juve ko con l’Albinoleffe', author:'', summary:'Seconda sconfitta consecutiva per la Juventus Under 20, battuta 2-1 a Vinovo. Keutgen porta avanti i bianconeri, poi Rinaldi ribalta la gara con una doppietta prima dell’intervallo. La squadra resta a due punti dopo quattro giornate e Padoin richiama il gruppo alle proprie responsabilità.', pages:'60', stars:3},
  {cat:'Next Gen', outlet:'Tuttosport', title:'C’è l’Ospitaletto per la Next Gen «Miglioriamo»', author:'', summary:'La Next Gen affronta l’Ospitaletto dopo una vittoria e due pareggi nelle prime tre partite. Brambilla sottolinea che la squadra ha raccolto meno di quanto prodotto e vede ancora ampi margini di crescita. Alcuni giovani sono stati aggregati alla prima squadra, passaggio che il tecnico considera fondamentale per il loro percorso.', pages:'78', stars:3},
  {cat:'Juventus Women', outlet:'Tuttosport', title:'Women, l’inizio è perfetto', author:'', summary:'La Juventus Women supera l’Inter 1-0 nella semifinale della Women’s Cup e porta a sette su sette le vittorie nelle gare ufficiali. Decide l’autorete di Van Diemen, nata da una situazione di calcio d’angolo. La finale è in programma sabato 19 settembre alle 18 a Viareggio contro la vincente di Sassuolo-Roma.', pages:'84', stars:3},
  {cat:'Prossimo avversario', outlet:'Tuttosport', title:'Aquilani recupera Bakola e lancia Esposito titolare', author:'', summary:'Aquilani chiede al Sassuolo coraggio e personalità senza trasformare la partita in un braccio di ferro con la Juventus. Bakola torna disponibile, Esposito è favorito su Bowie e resta aperto il ballottaggio Thorstvedt-Adzic. Berardi va verso una maglia dal primo minuto.', pages:'389', stars:3},
  {cat:'Europa League', outlet:'La Gazzetta dello Sport', title:'Il NEC si avvicina ai bianconeri con un ko pesante', author:'', summary:'Il NEC Nijmegen, prossimo avversario della Juventus in Europa League giovedì all’Allianz Stadium, arriva da una sconfitta per 3-0 sul campo del Cambuur: doppietta di Hamache e rete di Henstra. Per gli olandesi è la terza gara consecutiva senza vittorie, dopo il pareggio con l’Excelsior e il ko contro il Feyenoord.', pages:'214', stars:3},
  {cat:'Politica sportiva', outlet:'Corriere dello Sport Stadio', title:'Procura Figc apre fascicolo su Lucarelli', author:'', summary:'La Procura federale ha aperto un procedimento sulle dichiarazioni di Cristiano Lucarelli relative al divieto di trasferta per i tifosi del Livorno. L’obiettivo è verificare eventuali violazioni del codice di giustizia sportiva; in caso di deferimento il procedimento potrebbe portare a una sanzione.', pages:'89', stars:2}
];

const sources=['La Gazzetta dello Sport','Tuttosport','Corriere dello Sport Stadio','La Stampa','Libero Quotidiano','QN Sport'];
const clipKey='b918f471e2c7469ba0f0c328d6460041';
const stars=n=>'★'.repeat(n)+'☆'.repeat(5-n);

export default function Page(){
  return <main>
    <header>
      <div className="top"><div className="brand"><i>JUMP</i> PRESS</div><div className="edition">JUVENTUS · DAILY MEDIA INTELLIGENCE</div></div>
      <small>DOMENICA 13 SETTEMBRE 2026</small>
      <h1>Rassegna stampa <em>Juventus</em></h1>
      <p className="lead">La Juventus arriva alla trasferta con il Sassuolo in piena emergenza, ma il messaggio di Luciano Spalletti domina la rassegna: niente alibi e responsabilità da redistribuire tra chi è disponibile. Douglas Luiz e Koopmeiners diventano centrali, Pape Sarr torna tra le opzioni e davanti Kolo Muani cerca ancora il primo gol mentre cresce lo spazio per Woltemade. Sullo sfondo, Tuttosport segnala nuove prove d’addio con Milik, la Primavera cade ancora, la Next Gen cerca continuità e la Juventus Women conquista la finale di Women’s Cup.</p>
      <div className="stats"><div><b>18</b><span>pezzi selezionati</span></div><div><b>409</b><span>pagine analizzate</span></div><div><b>2</b><span>editoriali in apertura</span></div><div><b>3/3</b><span>sportivi con Juve in prima</span></div></div>
    </header>

    <section className="brief">
      <small>EXECUTIVE BRIEF</small><h2>La lettura complessiva della giornata</h2>
      <p className="intro">Il filo comune è la trasformazione forzata della Juventus. Gli infortuni riducono le alternative, ma Spalletti ribalta il racconto: la squadra deve essere giudicata da chi va in campo, non dagli assenti. Douglas Luiz e Koopmeiners diventano i riferimenti del centrocampo; Kolo Muani e Woltemade concentrano l’attenzione davanti, mentre il recupero di Sarr restituisce almeno una soluzione in più.</p>
      <div className="briefgrid">
        <div className="hot"><b>TEMA PRINCIPALE</b><h3>Niente alibi: Spalletti cambia la Juve</h3><p>Sette possibili titolari nuovi rispetto alla passata stagione e un assetto ridisegnato dall’emergenza. Il tecnico chiede responsabilità e prestazioni all’altezza del club.</p></div>
        <div className="delicate"><b>AREA DI ATTENZIONE</b><h3>Kolo e Woltemade sotto osservazione</h3><p>Kolo Muani cerca il primo gol stagionale; Woltemade può trovare spazio dall’inizio o insieme al francese. Sono i due volti più osservati dell’attacco.</p></div>
        <div className="positive"><b>NOTIZIE POSITIVE</b><h3>Sarr rientra, Women in finale</h3><p>Pape Sarr torna tra le opzioni di Spalletti. La Juventus Women supera l’Inter e raggiunge la finale di Women’s Cup.</p></div>
      </div>
    </section>

    <section className="sources">
      <small>DATI VERIFICATI SUL PDF</small><h2>Copertura Juventus del 13 settembre</h2>
      <p className="intro">La rassegna completa contiene <b>409 pagine</b>. La Juventus è richiamata in prima pagina da <b>La Gazzetta dello Sport</b>, <b>Corriere dello Sport Stadio</b> e <b>Tuttosport</b>: tutti e tre i quotidiani sportivi nazionali controllati. Le prime pagine di Corriere della Sera, Repubblica e La Stampa controllate non riportano invece un richiamo Juventus.</p>
      <div>{sources.map(s=><span key={s}>{s}</span>)}</div>
      <p><a href="/api/r20260913-6f9b2e61d4874e3a?key=d3e7c10b1a5f4e8796c24e3a8bd7f051" target="_blank" rel="noreferrer">Apri la rassegna completa · 409 pagine ↗</a></p>
    </section>

    <div className="sectiontitle"><small>RASSEGNA SELEZIONATA</small><h2>I 18 pezzi di oggi</h2></div>
    <section className="articles">{articles.map((a,i)=><article key={i}><div className="meta"><label><span>{a.cat}</span><b>{a.outlet}</b></label><div className="stars" title={`${a.stars} stelle su 5`}>{stars(a.stars)}</div></div><h2>{a.title}</h2>{a.author&&<aside>di {a.author}</aside>}<p>{a.summary}</p><a href={`/api/r20260913-clip?key=${clipKey}&pages=${encodeURIComponent(a.pages)}`} target="_blank" rel="noreferrer">Apri ritaglio completo <b>↗</b></a></article>)}</section>
    <footer><b>JUMP PRESS</b> · Rassegna Juventus · 13 settembre 2026<br/><span>18 pezzi selezionati · 409 pagine analizzate · 3/3 sportivi con Juve in prima pagina</span></footer>
  </main>
}
