const articles=[
['Editoriali','Tuttosport',"Non c’è un leader e non c’è pensiero",'Guido Vaciago','Il problema non è soltanto Kolo: i cinquanta milioni spesi hanno sottratto risorse a un centrocampo senza qualità, coraggio e carattere, dove Matic sarebbe servito. Douglas Luiz non basta e l’assenza di Locatelli rivela quanto contino i suoi equilibri. Alla difesa si può concedere una giornata storta dopo prove convincenti; non alla squadra l’assalto scriteriato finale. Mancano pensiero e leadership: affidarsi all’incostante Zhegrova rivela lo squilibrio mentale bianconero. Spalletti resta l’unico che possa raddrizzare la stagione.'],
['Editoriali','Corriere dello Sport','Lucio, ci vuole meno filosofia','Vittorio Oreggia','La prima sconfitta è la conseguenza di difficoltà già visibili: il Sassuolo blocca la lenta circolazione di Douglas Luiz e Koopmeiners, mentre gli esterni non trovano un finalizzatore. Sui due gol conclusivi la Juventus si espone in modo dilettantesco: responsabilità anche di Spalletti, cui serve più concretezza. Difendere Kolo non può diventare una formula senza scadenza. Positivo Nico Gonzalez, non soltanto per la traversa; ma le poche alternative e i nuovi ancora indietro mostrano che scricchiola l’intero progetto.'],
['Editoriali','La Stampa','Quella consueta crisi esistenziale','Vittorio Oreggia','La Juventus, mai brillante nelle prime tre giornate, torna alla sua crisi abituale: prima inconcludente, poi sconsiderata nei contropiedi concessi. Gli infortuni pesano, ma Spalletti deve trovare soluzioni concrete: la difesa di Kolo rischia di diventare una questione di principio. Le responsabilità coinvolgono anche un mercato tardivo e poco risolutivo: Woltemade non è mai stato prolifico, Sarr deve ritrovare la condizione e non si può chiedere al giovanissimo Alajbegovic di risolvere tutto. Zhegrova sfiora il salvataggio, prima del nuovo crollo.'],
['Editoriali','La Gazzetta dello Sport','Juve in confusione. Dopo 10 mesi Spalletti resta fermo al palo','Sebastiano Vernazza','Tre gol in contropiede bastano ad aprire una crisi tecnica: dopo dieci mesi, Spalletti non ha dato ordine alla Juventus. Che la doppietta arrivi dall’esubero Zhegrova e Nico Gonzalez sia tra i migliori mette in discussione anche la valutazione della rosa, mentre i nuovi non partono titolari. Vernazza teme un altro avvitamento come quello in Nazionale e propone a Elkann di chiamare Conte, ritenuto l’unico capace di ricostruire: è una sua indicazione, non una trattativa riferita.'],
['Editoriali','Libero','Aquilani fa piangere la Juve','Claudio Savelli','Il Sassuolo ha organizzazione e consapevolezza, la Juventus dipende dalle iniziative individuali. Aquilani ne inceppa la costruzione: Koopmeiners non sostituisce Locatelli, Douglas Luiz resta isolato e i difensori non si assumono la responsabilità di avviare l’azione. I cambi di Spalletti ravvivano l’attacco, ma compromettono l’equilibrio e preparano i due gol conclusivi. Le assenze contano soprattutto per l’insufficienza delle alternative: rispetto al Milan è un passo indietro, da correggere già contro il Nec.'],
['Juventus','Corriere della Sera','Senza difesa','','Il Sassuolo batte la Juventus 3-2: Zhegrova risponde prima a Esposito e poi a Bowie, ma al 94’ Adzic decide dopo un pallone perso da Kolo Muani, con i bianconeri nuovamente scoperti. La Juve resta a sette punti e rischia di ritrovarsi a cinque dalla vetta se Inter o Roma vinceranno questa sera.'],
['Juventus','La Gazzetta dello Sport','La rabbia di Spalletti. «In 8 sulla palla per vincere. Persa la ragione. Errore nostro»','','Spalletti si assume la responsabilità dell’assalto conclusivo: «Sono stato io a caricare i ragazzi per andare a prendere la vittoria». Riconosce la reazione, ma condanna la perdita di equilibrio. Su Kolo chiede più cattiveria e maggiori rifornimenti; di Zhegrova apprezza la pericolosità offensiva, senza ignorarne gli errori nelle scelte e nel ripiegamento.'],
['Juventus','La Gazzetta dello Sport','Vicario: «La Juve non può subire gol così»','','«La Juve non può subire due gol in quel modo»: Vicario denuncia l’eccessiva spregiudicatezza, nonostante il problema fosse stato affrontato in settimana. Chiede calma e fiducia nella qualità della squadra per costruire l’occasione giusta, senza perdere equilibrio. Le assenze non giustificano la sconfitta: «Non possiamo nasconderci dietro agli alibi».'],
['Juventus','La Gazzetta dello Sport','Kolo gioca a nascondino. Il francese è un problema','','Kolo Muani resta senza gol dopo quattro giornate: fatica a rendersi disponibile e a trovare la posizione, pur partecipando al secondo pareggio. Woltemade deve ancora inserirsi e Spalletti cerca un assetto che li valorizzi. Zhegrova segna le prime reti alla trentesima presenza juventina, interrompendo un digiuno personale di 658 giorni e rimettendo in discussione le gerarchie offensive.'],
['Juventus','Tuttosport','Cambiaso e McKennie mettono il Nec nel mirino','','Cambiaso e McKennie puntano a tornare in gruppo domani per il Nec; il forfait dell’azzurro è precauzionale. Lucumi è uscito zoppicando: possibili rotazioni con Gatti e Kelly, mentre Woltemade può partire titolare. Per Thuram e Locatelli l’attesa arriva almeno alle prime settimane del 2027; Yildiz è atteso dopo la sosta di novembre, Boga, Ekhator e Cabal entro metà ottobre.'],
['Juventus','La Gazzetta dello Sport','Signora storica. L’unico italiano gioca in porta','','Per la prima volta in Serie A la Juventus schiera dall’inizio dieci giocatori di movimento stranieri: l’unico italiano è Vicario. Era già capitato di partire con dieci stranieri, ma mai con il solo rappresentante azzurro tra i pali. Gatti, Rugani, Owusu, Pagnucco e Pinsoglio sono in panchina.'],
['Juventus','La Gazzetta dello Sport','Adzic punisce la sua Juve. Entra, segna e non esulta. «Emozioni indimenticabili»','','Un anno dopo il gol decisivo all’Inter, Adzic condanna la Juventus al 94’: in prestito al Sassuolo, conta tre reti e un assist in cinque partite. «A quest’età devo crescere e giocare con costanza». Aquilani rivendica la scelta di inserirlo a gara avanzata: «Sapevo che avrebbe fatto la differenza entrando con le squadre più stanche».'],
['Mercato','Corriere dello Sport','Matic illumina. Kolo innocuo','','Il Corriere segnala l’interesse della Juventus per Lipani in vista del prossimo mercato: contro i bianconeri conferma le qualità di mezzala. Matic guida il Sassuolo e serve il pallone del vantaggio a Esposito. Non vengono indicate trattative, offerte o valutazioni per Lipani.'],
['Mercato','La Gazzetta dello Sport','Matic è un professore, per Esposito una notte da re','','La Gazzetta definisce Bakola «osservato speciale della Juve»: appena entrato, manda Berardi verso la porta con un lancio e mostra corsa e qualità. Il riferimento riguarda l’attenzione bianconera sul giocatore, senza indicazioni su offerte o negoziati.'],
['Juventus Youth','Tuttosport','Licina. La Bosnia prova il dribbling','','La Bosnia intensifica il corteggiamento di Adin Licina dopo il buon avvio alla Cremonese, dove gioca in prestito dalla Juventus. Il diciannovenne ha rappresentato la Germania nelle selezioni giovanili, ma le origini familiari gli aprono anche le possibilità bosniaca e montenegrina. Sarajevo vorrebbe affiancarlo ad Alajbegovic: la scelta non è ancora fatta.'],
['Next Gen','Tuttosport','Tante assenze: la Next Gen crolla a Ospitaletto','','Prima sconfitta per la Next Gen, battuta 3-0 senza Owusu, Oboavwoduo e Pagnucco, chiamati in prima squadra, e lo squalificato Corradi. Sul terzo gol resta il dubbio per una trattenuta su Konaté, non sanzionata dopo il controllo FVS. Brambilla: «Siamo stati poco puliti tecnicamente, abbiamo forzato tante giocate»; una battuta d’arresto da trasformare in crescita.'],
['Juventus Women','Corriere di Torino','In finale per la J Women ci sarà ancora la Roma','','Settima vittoria in otto partite per Guerrero: l’1-0 sull’Inter porta la Juventus alla finale di Women’s Cup contro la Roma, sabato 19 settembre alle 18 a Viareggio. «Il primo obiettivo era fare squadra. Le ragazze sono state bravissime fin da subito a crearla». Sarà il nono confronto in finale fra le due società.'],
['Juventus Women','Tuttosport','La Juve in finale con la Roma','','La Juventus ha chiuso per la centrocampista giapponese Manaka Hayashi e punta ad altri due-tre acquisti prima della fine del mercato. Intanto prepara la finale di Women’s Cup contro la Roma, qualificata con il 7-1 sul Sassuolo.'],
['Arbitri','Corriere dello Sport','Sacchi la tiene. Idzes no mano, non c’è rigore','','Per la moviola non c’è rigore sul presunto tocco di Idzes: il pallone sembra colpire il petto di Bremer e l’eventuale mano non sarebbe comunque punibile. Regolare il gol di Esposito, tenuto in gioco da Kalulu; corretto annullare l’altra rete neroverde per il doppio fuorigioco di Adzic e Cinquegrano.'],
['Politica sportiva','La Gazzetta dello Sport','Malagò. La linea della Figc','','Chinè ribadisce la richiesta di archiviazione: per la Procura FIGC, essere in regola con il tesseramento non significa dover essere già tesserati per essere eletti. Taucer sostiene l’interpretazione opposta. Malagò replica: «La mia elezione è valida». Il caso non sarà discusso nella Giunta CONI di domani; il contrasto resta aperto.'],
['Politica sportiva','Il Fatto Quotidiano','Coni & Figc. Paratici, malagiustizia sportiva e la Fiorentina nei guai','Paolo Ziliani','Ziliani contrappone il rigore di Taucer sul caso Malagò alla mancata opposizione al patteggiamento Juventus-FIGC del 2023. Giudica incongrua l’ammenda da 718 mila euro e sostiene che un processo avrebbe portato alla Serie B e alla radiazione di Agnelli e Paratici. Collega a quella scelta il ritorno operativo di Paratici e il caos della Fiorentina: 150 milioni spesi, Grosso esonerato dopo tre partite e Vanoli richiamato, con entrambi gli allenatori a stipendio.'],
['Nazionale','La Gazzetta dello Sport','Bianchedi capodelegazione. Risposta Anac in due giorni','','È atteso entro metà settimana il parere dell’ANAC sulla compatibilità fra il ruolo di capodelegazione della Nazionale e quello di vicepresidente vicario del CONI ricoperto da Diana Bianchedi. La FIGC ha inviato ulteriori chiarimenti venerdì. Bianchedi conferma il confronto con Buonfiglio e Malagò: «stiamo cercando di fare le cose per bene».'],
['Nazionale','La Gazzetta dello Sport','Novità Romano','','La FIFA ha autorizzato il cambio di nazionalità sportiva di Alessandro Romano, ventenne del Cagliari nato in Svizzera da genitori italiani: Mancini lo convocherà venerdì. Il regista arriva in un reparto privo dell’infortunato Locatelli e con Ricci poco impiegato. L’Italia affronterà quattro partite in undici giorni, cominciando dal Belgio il 25 settembre a Roma.']
];

const clipIds=['NBGKLI','NBGM10','NBG5YI','NBGHJ8','NBG6FB','NBGBD4','NBGH8Z','NBGH7B','NBGHO2','NBGME1','NBGH3O','NBGH3X','NBGKZ7','NBGH5Q','NBGMO9','NBGMIS','NBGFWV','NBGMHV','NBGM0B','NBGH9R','NBG1OR','NBGHAM','NBGH5T'];

const clipUrl=(i)=>`/api/r20260914-article?id=${clipIds[i]}`;

export default function Page(){
return <main>
<header><div className="top"><div className="brand"><i>JUMP</i> PRESS</div><div className="edition">JUVENTUS · DAILY MEDIA INTELLIGENCE</div></div><small>LUNEDÌ 14 SETTEMBRE 2026</small><h1>Rassegna stampa <em>Juventus</em></h1><p className="lead">La Juventus cade contro il Sassuolo: la doppietta di Zhegrova non basta a compensare gli squilibri di una squadra che continua a faticare in attacco e si scopre fragile anche dietro. Spalletti si assume la responsabilità dell’assalto finale, mentre Kolo Muani resta senza gol. Giovedì arriva il debutto europeo contro il Nec: Cambiaso e McKennie puntano al recupero, Woltemade alla prima da titolare.</p><div className="stats"><div><b>23</b><span>pezzi selezionati</span></div><div><b>316</b><span>pagine analizzate</span></div><div><b>212</b><span>voci nell’indice</span></div><div><b>5</b><span>editoriali in apertura</span></div></div></header>
<section className="brief"><small>EXECUTIVE BRIEF</small><h2>La lettura complessiva della giornata</h2><p className="intro">Il tema dominante è la perdita di equilibrio della Juventus. La sconfitta di Reggio Emilia riapre il dibattito su leadership, qualità del centrocampo e rendimento offensivo. Kolo Muani resta a zero gol, mentre Zhegrova è la risposta più concreta. Spalletti deve già preparare la reazione europea contro il NEC, con Cambiaso e McKennie verso il recupero e Woltemade candidato alla prima da titolare.</p></section>
<section className="sources"><small>DATI VERIFICATI SULLA RASSEGNA</small><h2>Copertura Juventus del 14 settembre</h2><p className="intro">La rassegna completa analizzata contiene <b>316 pagine</b> e <b>212 voci d’indice</b>. Nella selezione finale sono stati mantenuti 23 pezzi.</p><p><a href="/api/r20260914-full" target="_blank" rel="noreferrer">Apri la rassegna completa · 316 pagine ↗</a></p></section>
<div className="sectiontitle"><small>RASSEGNA SELEZIONATA</small><h2>I 23 pezzi di oggi</h2></div>
<section className="articles">{articles.map((a,i)=><article key={i}>
<div className="meta"><label><span>{a[0]}</span><b>{a[1]}</b></label></div>
<h2>{a[2]}</h2>{a[3]&&<aside>di {a[3]}</aside>}<p>{a[4]}</p>
<div style={{marginTop:'22px',border:'1px solid #d9d9d9',borderRadius:'12px',overflow:'hidden',background:'#f6f6f6'}}>
<div style={{display:'flex',alignItems:'center',justifyContent:'space-between',gap:'12px',padding:'12px 14px',background:'#111',color:'#fff'}}><b style={{fontSize:'13px',letterSpacing:'.06em'}}>RITAGLIO ORIGINALE</b><a href={clipUrl(i)} target="_blank" rel="noreferrer" style={{color:'#fff',fontWeight:700,textDecoration:'underline'}}>Apri a pagina intera ↗</a></div>
<iframe src={clipUrl(i)} title={`Ritaglio completo — ${a[2]}`} style={{display:'block',width:'100%',height:'520px',border:0,background:'#fff'}} />
<div style={{padding:'12px 14px',background:'#fff'}}><a href={clipUrl(i)} target="_blank" rel="noreferrer" style={{display:'inline-block',fontWeight:800,textDecoration:'none'}}>APRI RITAGLIO COMPLETO ↗</a></div>
</div>
</article>)}</section>
<footer><b>JUMP PRESS</b> · Rassegna Juventus · 14 settembre 2026<br/><span>23 pezzi selezionati · 316 pagine analizzate · 212 voci d’indice</span></footer>
</main>
}