'use client';
import {useEffect,useLayoutEffect,useRef,useState} from 'react';
import PdfOutline from './PdfOutline';
import {filterPdfOutline} from '../../lib/pdf-outline-search';
import {attachPdfPan} from '../../lib/pdf-pan';
function PdfSheet({doc,number,size,scale,root,onError,onNavigate}){
 const box=useRef(null),canvas=useRef(null),[near,setNear]=useState(false),[links,setLinks]=useState([]);
 useEffect(()=>{const observer=new IntersectionObserver(([entry])=>setNear(entry.isIntersecting),{root:root.current,rootMargin:'800px 0px'});observer.observe(box.current);return()=>observer.disconnect();},[root]);
 useEffect(()=>{let dead=false,render;const target=canvas.current;if(!near){target.width=0;target.height=0;return;}
 (async()=>{try{const page=await doc.getPage(number);if(dead)return;const base=page.getViewport({scale:1});const annotations=await page.getAnnotations();if(dead)return;setLinks(annotations.filter(a=>a.subtype==='Link'&&a.dest).map(a=>{const r=[...base.convertToViewportPoint(a.rect[0],a.rect[1]),...base.convertToViewportPoint(a.rect[2],a.rect[3])];return {...a,box:{left:Math.min(r[0],r[2])/base.width*100+'%',top:Math.min(r[1],r[3])/base.height*100+'%',width:Math.abs(r[2]-r[0])/base.width*100+'%',height:Math.abs(r[3]-r[1])/base.height*100+'%'}};}));const viewport=page.getViewport({scale:1.5*scale});target.width=viewport.width;target.height=viewport.height;render=page.render({canvasContext:target.getContext('2d'),viewport});await render.promise;}catch(e){if(!dead&&e.name!=='RenderingCancelledException')onError('Impossibile mostrare una pagina. Chiudi e riapri il PDF.');}})();return()=>{dead=true;render?.cancel();};},[doc,number,near,scale,onError]);
 return <div ref={box} className="summary-pdf-sheet" data-pdf-page={number} style={{aspectRatio:`${size.width} / ${size.height}`}}><canvas ref={canvas} role="img" aria-label={`Pagina ${number} della rassegna`}/>{links.map((link,i)=><button key={i} className="pdf-internal-link" style={link.box} aria-label={link.contentsObj?.str||'Vai al contenuto collegato'} title={link.contentsObj?.str||'Vai al contenuto collegato'} onClick={()=>onNavigate(link)}/>)}</div>;
}
export default function PdfPreview({onClose,kind='edition',date,sections=null,includeClips=false,pdfEndpoint='/summary/pdf'}){
 const isSummary=kind==='summary',params=new URLSearchParams();params.set('kind',kind);if(sections)params.set('sections',sections.join(','));if(includeClips)params.set('clips','1');const pdfUrl=pdfEndpoint+(pdfEndpoint.includes('?')?'&':'?')+params.toString();
 const dialog=useRef(null),paper=useRef(null),zoomAnchor=useRef(null);
 const [doc,setDoc]=useState(null),[sizes,setSizes]=useState([]),[current,setCurrent]=useState(1),[scale,setScale]=useState(1),[error,setError]=useState('');const pages=sizes.length;const [pageInput,setPageInput]=useState('1');useEffect(()=>setPageInput(String(current)),[current]);
 const [outline,setOutline]=useState([]),[indexOpen,setIndexOpen]=useState(false);const indexButton=useRef(null),indexPanel=useRef(null);const [search,setSearch]=useState('');const filteredOutline=filterPdfOutline(outline,search);
 useEffect(()=>{if(indexOpen)indexPanel.current?.querySelector('input')?.focus();},[indexOpen]);
 useEffect(()=>attachPdfPan(paper.current),[]);
 useEffect(()=>{const focus=document.activeElement;dialog.current.showModal();let dead=false,task,worker;const overflow=document.body.style.overflow;document.body.style.overflow='hidden';
 (async()=>{try{const pdfjs=await import(/* webpackIgnore: true */ '/pdfjs/pdf.mjs');if(dead)return;pdfjs.GlobalWorkerOptions.workerSrc='/pdfjs/pdf.worker.mjs';worker=new pdfjs.PDFWorker();task=pdfjs.getDocument({url:pdfUrl+(pdfUrl.includes('?')?'&':'?')+'inline=1',worker,standardFontDataUrl:'/pdfjs/standard_fonts/',wasmUrl:'/pdfjs/wasm/',cMapUrl:'/pdfjs/cmaps/',cMapPacked:true,isEvalSupported:false});const document=await task.promise;if(dead)return;const dimensions=[];for(let n=1;n<=document.numPages;n++){if(dead)return;const p=await document.getPage(n),v=p.getViewport({scale:1});dimensions.push({width:v.width,height:v.height});}if(!dead){setDoc(document);setSizes(dimensions);setOutline(await document.getOutline()||[]);}}catch{if(!dead)setError(includeClips?'Impossibile preparare il PDF con tutti i ritagli richiesti. Riprova oppure disattiva l’opzione ritagli.':'PDF non disponibile. Chiudi e riprova.');}})();return()=>{dead=true;document.body.style.overflow=overflow;task?.destroy().catch(()=>{});worker?.destroy();focus?.focus();};},[]);
 useEffect(()=>{if(!pages)return;const area=paper.current;let frame;const update=()=>{frame=null;const y=area.getBoundingClientRect().top+Math.min(120,area.clientHeight*.25);let best=1;for(const sheet of area.querySelectorAll('[data-pdf-page]')){if(sheet.getBoundingClientRect().top<=y)best=Number(sheet.dataset.pdfPage);else break;}setCurrent(best);};const scroll=()=>{if(!frame)frame=requestAnimationFrame(update);};area.addEventListener('scroll',scroll,{passive:true});update();return()=>{area.removeEventListener('scroll',scroll);cancelAnimationFrame(frame);};},[pages,scale]);
 useLayoutEffect(()=>{const anchor=zoomAnchor.current;if(!anchor)return;const area=paper.current,sheet=area.querySelector(`[data-pdf-page="${anchor.page}"]`);if(sheet)area.scrollTop+=sheet.getBoundingClientRect().top-area.getBoundingClientRect().top+anchor.fraction*sheet.offsetHeight;zoomAnchor.current=null;},[scale]);
 const zoom=delta=>{const area=paper.current,sheet=area.querySelector(`[data-pdf-page="${current}"]`);if(sheet)zoomAnchor.current={page:current,fraction:(area.getBoundingClientRect().top-sheet.getBoundingClientRect().top)/sheet.offsetHeight};setScale(s=>Math.max(.75,Math.min(2,s+delta)));};
 const fit=()=>{const area=paper.current,sheet=area.querySelector(`[data-pdf-page="${current}"]`);if(sheet)zoomAnchor.current={page:current,fraction:(area.getBoundingClientRect().top-sheet.getBoundingClientRect().top)/sheet.offsetHeight};setScale(1);area.scrollLeft=0;};
 const go=n=>{const area=paper.current,sheet=area.querySelector(`[data-pdf-page="${n}"]`);if(sheet){area.scrollTo({top:area.scrollTop+sheet.getBoundingClientRect().top-area.getBoundingClientRect().top-16,behavior:'auto'});setCurrent(n);}};
 const commitPage=()=>{const value=pageInput.trim();if(!/^\d+$/.test(value)){setPageInput(String(current));return;}const n=Math.max(1,Math.min(pages,Number(value)));setPageInput(String(n));go(n);};
 const selectOutline=async (item,fromIndex=true)=>{try{const dest=typeof item.dest==='string'?await doc.getDestination(item.dest):item.dest;if(!dest)return;const n=typeof dest[0]==='number'?dest[0]+1:await doc.getPageIndex(dest[0])+1;const p=await doc.getPage(n),v=p.getViewport({scale:1});const y=dest[1]?.name==='XYZ'&&typeof dest[3]==='number'?v.convertToViewportPoint(0,dest[3])[1]/v.height:0;const area=paper.current,sheet=area.querySelector(`[data-pdf-page="${n}"]`);if(sheet)area.scrollTo({top:area.scrollTop+sheet.getBoundingClientRect().top-area.getBoundingClientRect().top+y*sheet.offsetHeight-16});setCurrent(n);if(fromIndex){setIndexOpen(false);indexButton.current?.focus();}else paper.current?.focus();}catch{setError('Impossibile raggiungere la voce dell’indice.');}};
 return <dialog ref={dialog} className="summary-pdf-preview summary-pdf-continuous" aria-label={isSummary?'Anteprima Summary':'Anteprima PDF della rassegna'} onCancel={event=>{if(indexOpen){event.preventDefault();setIndexOpen(false);indexButton.current?.focus();}else onClose();}}><header><div><strong>{isSummary?'Summary · una pagina':sections?'Sezioni selezionate':'Anteprima PDF'}</strong><small>Rassegna Juventus · {date}{includeClips?' · Con ritagli originali':''}</small></div><a href={pdfUrl} download>{isSummary?'Scarica Summary':'Scarica PDF'}</a><button onClick={onClose} aria-label="Chiudi anteprima PDF">×</button></header>
 {indexOpen&&<aside className="pdf-outline-panel" ref={indexPanel} aria-label="Indice del PDF"><div><strong>Indice</strong><button type="button" aria-label="Chiudi indice" onClick={()=>{setIndexOpen(false);indexButton.current?.focus();}}>×</button></div><label className="pdf-index-search">Cerca per titolo o testata<input type="search" value={search} onChange={event=>setSearch(event.target.value)} placeholder="Es. Gazzetta, Spalletti…"/></label>{filteredOutline.length?<PdfOutline items={filteredOutline} onSelect={selectOutline} expanded={Boolean(search.trim())}/>:<p role="status">Nessun risultato per questa ricerca.</p>}</aside>}
 <div ref={paper} tabIndex={0} aria-label="Pagine PDF a scorrimento" className={'summary-pdf-paper'+(scale>1?' pdf-pan-enabled':'')}>{error?<p role="alert">{error}</p>:!pages?<p role="status">Preparazione del PDF…</p>:<div className="summary-pdf-stack" style={{width:`${scale*100}%`,maxWidth:'none'}}>{sizes.map((size,i)=><PdfSheet key={i} doc={doc} number={i+1} size={size} scale={scale} root={paper} onError={setError} onNavigate={item=>selectOutline(item,false)}/>)}</div>}</div>
 <nav aria-label="Navigazione PDF">{outline.length>0&&<button ref={indexButton} className="pdf-index-toggle" aria-expanded={indexOpen} onClick={()=>setIndexOpen(v=>!v)}>Indice</button>}<button aria-label="Pagina PDF precedente" disabled={!pages||current===1} onClick={()=>go(current-1)}>←</button><span><span className="pdf-page-prefix">Pagina </span><input className="pdf-page-input" aria-label="Numero pagina PDF" inputMode="numeric" pattern="[0-9]*" value={pageInput} disabled={!pages} onFocus={event=>event.target.select()} onChange={event=>setPageInput(event.target.value)} onBlur={commitPage} onKeyDown={event=>{if(event.key==='Enter'){event.preventDefault();commitPage();event.currentTarget.blur();}if(event.key==='Escape'){event.preventDefault();event.stopPropagation();setPageInput(String(current));}}}/> di {pages||'…'}</span><button aria-label="Pagina PDF successiva" disabled={!pages||current===pages} onClick={()=>go(current+1)}>→</button><span className="pdf-control-divider"/><button disabled={!pages||scale<=.75} onClick={()=>zoom(-.25)} aria-label="Riduci PDF">−</button><span className="pdf-zoom-value">{Math.round(scale*100)}%</span><button disabled={!pages||scale>=2} onClick={()=>zoom(.25)} aria-label="Ingrandisci PDF">+</button><button className="pdf-fit-button" disabled={!pages} aria-label="Adatta PDF alla larghezza" onClick={fit}>Adatta</button></nav></dialog>;
}
