'use client';
import {useEffect,useRef,useState} from 'react';
import LoginDialog from '../components/LoginDialog';
export default function SidebarEditorTools({children,hideInstructions=false}){
 const [authenticated,setAuthenticated]=useState(false),[data,setData]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(false),[exiting,setExiting]=useState(false),[saving,setSaving]=useState(false),[saved,setSaved]=useState('');
 const dialog=useRef(null),trigger=useRef(null),textEditor=useRef(null);
 useEffect(()=>{const open=()=>openInstructions();window.addEventListener('jump-open-instructions',open);return()=>window.removeEventListener('jump-open-instructions',open);});
 useEffect(()=>{let active=true;fetch('/api/auth/session',{cache:'no-store'}).then(async response=>{if(!response.ok)throw Error('Accesso non verificabile. Ricarica la pagina.');return response.json();}).then(result=>{if(active)setAuthenticated(result.authenticated);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[]);
 async function openInstructions(){dialog.current.showModal();if(data?.localEditable)return;setLoading(true);setError('');try{const response=await fetch('/api/editor/instructions',{cache:'no-store'}),result=await response.json();if(!response.ok)throw Error(result.error||'Istruzioni non disponibili.');if(typeof result.text!=='string')throw Error('Istruzioni non disponibili.');setData(result);}catch(e){setError(e.message);}finally{setLoading(false);}}
 function goToCategories(){const el=textEditor.current;if(!el)return;const start=data.text.indexOf('CATEGORIE E ORDINE'),end=data.text.indexOf('CAPPELLO INIZIALE',start);if(start<0)return;
 const mirror=document.createElement('div'),style=getComputedStyle(el);for(const key of ['font','lineHeight','padding','boxSizing','letterSpacing'])mirror.style[key]=style[key];Object.assign(mirror.style,{position:'absolute',visibility:'hidden',whiteSpace:'pre-wrap',overflowWrap:'break-word',width:el.clientWidth+'px'});mirror.textContent=data.text.slice(0,start);document.body.appendChild(mirror);const height=mirror.scrollHeight;mirror.remove();el.focus();el.setSelectionRange(start,end>start?end:start);el.scrollTop=Math.max(0,height-30);
 }
 async function saveLocal(){setSaving(true);setError('');setSaved('');try{const response=await fetch('/api/editor/instructions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:data.text,localRevision:data.localRevision})}),result=await response.json();if(!response.ok)throw Error(result.error||'Salvataggio non riuscito.');setData(result);setSaved('Salvato solo in locale.');}catch(e){setError(e.message);}finally{setSaving(false);}}
 async function logout(){setExiting(true);setError('');try{const response=await fetch('/api/auth/logout',{method:'POST'});if(!response.ok)throw Error('Uscita non riuscita. Riprova.');window.location.assign('/');}catch(e){setError(e.message);setExiting(false);}}
 return <>
 {authenticated&&!hideInstructions&&<button ref={trigger} className="summary-editor-access" type="button" aria-haspopup="dialog" onClick={openInstructions}><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" aria-hidden="true"><path d="M5 3h14v18H5zM8 7h8M8 11h8M8 15h5"/></svg><span>Istruzioni</span></button>}
 {children}
 {authenticated?<button className="summary-editor-access" type="button" disabled={exiting} onClick={logout}><span aria-hidden="true">↪</span><span>{exiting?'Uscita…':'Esci'}</span></button>:<LoginDialog><span aria-hidden="true">↗</span><span>Accesso editor</span></LoginDialog>}
 {error&&!dialog.current?.open&&<p className="sidebar-access-error" role="alert">{error}</p>}
 <dialog ref={dialog} className="instructions-dialog" aria-labelledby="instructions-title" onClick={e=>{if(e.target!==e.currentTarget)return;const r=e.currentTarget.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.currentTarget.close();}} onClose={()=>trigger.current?.focus()}>
 <header><div><small>{data?.localEditable?'MODIFICA LOCALE':'SOLO LETTURA'}</small><h2 id="instructions-title">Istruzioni GPT</h2>{data&&<p>{data.localPreview?'Anteprima locale · base versione ':'Versione '}{data.version}{data.instructionProfile?' · '+data.instructionProfile:''}</p>}</div><button type="button" aria-label="Chiudi istruzioni" onClick={()=>dialog.current.close()}>×</button></header>
 {loading&&<p role="status">Caricamento delle istruzioni correnti…</p>}{error&&<p role="alert">{error}{data?' Il testo sottostante è l’ultima versione caricata.':''}</p>}
 {data&&(data.localEditable?<><div className="instructions-edit-actions"><button type="button" onClick={goToCategories}>Vai a Categorie e ordine</button><button type="button" disabled={saving||loading} onClick={saveLocal}>{saving?'Salvataggio…':'Salva in locale'}</button><span role="status">{saved||'Le modifiche non vengono pubblicate online.'}</span></div><textarea ref={textEditor} className="instructions-editable" aria-label="Testo istruzioni GPT modificabile in locale" spellCheck={false} value={data.text} onChange={e=>{setData({...data,text:e.target.value});setSaved('Modifiche non salvate');}}/></>:<pre className="instructions-readonly">{data.text}</pre>)}
 </dialog>
 </>;
}
